-- Test BenchVHDL for IBM SMS ALD group AddressRegisterCtrls
-- Title: AddressRegisterCtrls
-- IBM Machine Name 1411
-- Generated by GenerateHDL on 10/5/2020 12:33:59 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;  -- For use in test benches only
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity AddressRegisterCtrls_tb is
end AddressRegisterCtrls_tb;

architecture behavioral of AddressRegisterCtrls_tb is

	-- Component Declaration for the Unit Under Test (UUT)

	component AddressRegisterCtrls
	    Port (
		FPGA_CLK: in STD_LOGIC;
		PS_A_CYCLE_CTRL: in STD_LOGIC;
		PS_C_CYCLE_CTRL: in STD_LOGIC;
		PS_B_CYCLE_CTRL: in STD_LOGIC;
		PS_D_CYCLE_CTRL: in STD_LOGIC;
		PS_NO_SCAN_CTRL: in STD_LOGIC;
		PS_NO_OR_1ST_OR_2ND_OR_3RD_SCAN_CTRL: in STD_LOGIC;
		PS_MPLY_OP_CODE: in STD_LOGIC;
		PS_MPLY_OR_DIV_OP_CODES: in STD_LOGIC;
		PS_ARITH_TYPE_OP_CODES: in STD_LOGIC;
		MS_TABLE_SEARCH_A_CYCLE_U_CTRL: in STD_LOGIC;
		PS_UNITS_CTRL_LATCH: in STD_LOGIC;
		MS_BODY_CTRL_LATCH: in STD_LOGIC;
		PS_BODY_CTRL_LATCH: in STD_LOGIC;
		MS_EXTENSION_CTRL_LATCH: in STD_LOGIC;
		MS_MQ_CTRL_LATCH: in STD_LOGIC;
		PS_FILE_OP: in STD_LOGIC;
		MS_A_AR_RO_CTRL_STAR_ARITH: out STD_LOGIC;
		MS_B_AR_RO_CTRL_STAR_ARITH: out STD_LOGIC;
		PS_C_AR_RO_CTRL_STAR_ARITH: out STD_LOGIC;
		PS_D_AR_RO_CTRL_STAR_ARITH: out STD_LOGIC;
		MS_MPLY_DOT_NO_SCAN_CTRL_DOT_C_CY_CTRL: out STD_LOGIC);
	end component;

	-- Inputs

	signal FPGA_CLK: STD_LOGIC := '0';
	signal PS_A_CYCLE_CTRL: STD_LOGIC := '0';
	signal PS_C_CYCLE_CTRL: STD_LOGIC := '0';
	signal PS_B_CYCLE_CTRL: STD_LOGIC := '0';
	signal PS_D_CYCLE_CTRL: STD_LOGIC := '0';
	signal PS_NO_SCAN_CTRL: STD_LOGIC := '0';
	signal PS_NO_OR_1ST_OR_2ND_OR_3RD_SCAN_CTRL: STD_LOGIC := '0';
	signal PS_MPLY_OP_CODE: STD_LOGIC := '0';
	signal PS_MPLY_OR_DIV_OP_CODES: STD_LOGIC := '0';
	signal PS_ARITH_TYPE_OP_CODES: STD_LOGIC := '0';
	signal MS_TABLE_SEARCH_A_CYCLE_U_CTRL: STD_LOGIC := '1';
	signal PS_UNITS_CTRL_LATCH: STD_LOGIC := '0';
	signal MS_BODY_CTRL_LATCH: STD_LOGIC := '1';
	signal PS_BODY_CTRL_LATCH: STD_LOGIC := '0';
	signal MS_EXTENSION_CTRL_LATCH: STD_LOGIC := '1';
	signal MS_MQ_CTRL_LATCH: STD_LOGIC := '1';
	signal PS_FILE_OP: STD_LOGIC := '0';

	-- Outputs

	signal MS_A_AR_RO_CTRL_STAR_ARITH: STD_LOGIC;
	signal MS_B_AR_RO_CTRL_STAR_ARITH: STD_LOGIC;
	signal PS_C_AR_RO_CTRL_STAR_ARITH: STD_LOGIC;
	signal PS_D_AR_RO_CTRL_STAR_ARITH: STD_LOGIC;
	signal MS_MPLY_DOT_NO_SCAN_CTRL_DOT_C_CY_CTRL: STD_LOGIC;

-- START USER TEST BENCH DECLARATIONS

-- The user test bench declarations, if any, must be
-- placed AFTER the line starts with the first line of text 
-- with -- START USER TEST BENCH DECLARATIONS and ends
-- with the line containing -- END (and the rest of the line) below.
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

   constant HDL_C_BIT: integer := 7;
   constant HDL_WM_BIT: integer := 6;
   constant HDL_B_BIT: integer := 5;
   constant HDL_A_BIT: integer := 4;
   constant HDL_8_BIT: integer := 3;
   constant HDL_4_BIT: integer := 2;
   constant HDL_2_BIT: integer := 1;
   constant HDL_1_BIT: integer := 0;

   constant MX_X1A_POS: integer := 7;
   constant MX_X6A_POS: integer := 8;

procedure check1(
    checked: in STD_LOGIC;
    val: in STD_LOGIC;
    testname: in string;
    test: in string) is
    begin    
    assert checked = val report testname & " (" & test & ") failed." severity failure;
    end procedure;
      


   -- Your test bench declarations go here

-- END USER TEST BENCH DECLARATIONS
   

	begin

	-- Instantiate the Unit Under Test (UUT)

	UUT: AddressRegisterCtrls port map(
		FPGA_CLK => FPGA_CLK,
		PS_A_CYCLE_CTRL => PS_A_CYCLE_CTRL,
		PS_C_CYCLE_CTRL => PS_C_CYCLE_CTRL,
		PS_B_CYCLE_CTRL => PS_B_CYCLE_CTRL,
		PS_D_CYCLE_CTRL => PS_D_CYCLE_CTRL,
		PS_NO_SCAN_CTRL => PS_NO_SCAN_CTRL,
		PS_NO_OR_1ST_OR_2ND_OR_3RD_SCAN_CTRL => PS_NO_OR_1ST_OR_2ND_OR_3RD_SCAN_CTRL,
		PS_MPLY_OP_CODE => PS_MPLY_OP_CODE,
		PS_MPLY_OR_DIV_OP_CODES => PS_MPLY_OR_DIV_OP_CODES,
		PS_ARITH_TYPE_OP_CODES => PS_ARITH_TYPE_OP_CODES,
		MS_TABLE_SEARCH_A_CYCLE_U_CTRL => MS_TABLE_SEARCH_A_CYCLE_U_CTRL,
		PS_UNITS_CTRL_LATCH => PS_UNITS_CTRL_LATCH,
		MS_BODY_CTRL_LATCH => MS_BODY_CTRL_LATCH,
		PS_BODY_CTRL_LATCH => PS_BODY_CTRL_LATCH,
		MS_EXTENSION_CTRL_LATCH => MS_EXTENSION_CTRL_LATCH,
		MS_MQ_CTRL_LATCH => MS_MQ_CTRL_LATCH,
		PS_FILE_OP => PS_FILE_OP,
		MS_A_AR_RO_CTRL_STAR_ARITH => MS_A_AR_RO_CTRL_STAR_ARITH,
		MS_B_AR_RO_CTRL_STAR_ARITH => MS_B_AR_RO_CTRL_STAR_ARITH,
		PS_C_AR_RO_CTRL_STAR_ARITH => PS_C_AR_RO_CTRL_STAR_ARITH,
		PS_D_AR_RO_CTRL_STAR_ARITH => PS_D_AR_RO_CTRL_STAR_ARITH,
		MS_MPLY_DOT_NO_SCAN_CTRL_DOT_C_CY_CTRL => MS_MPLY_DOT_NO_SCAN_CTRL_DOT_C_CY_CTRL);

-- START USER TEST BENCH PROCESS

-- The user test bench code MUST be placed between the
-- line that starts with the first line of text that
-- begins with "-- START USERS TEST BENCH PROCESS" 
-- and ends with "-- END"
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

-- 
-- TestBenchFPGAClock.vhdl
--
-- Process to simulate the FPGA clock for a VHDL test bench
--

fpga_clk_process: process

   constant clk_period : time := 10 ns;

   begin
      fpga_clk <= '0';
      wait for clk_period / 2;
      fpga_clk <= '1';
      wait for clk_period / 2;
   end process;

--
-- End of TestBenchFPGAClock.vhdl
--   

-- Place your test bench code in the uut_process

uut_process: process

   variable testName: string(1 to 18);
   variable subtest: integer;
   variable tv: std_logic_vector(25 downto 0);
   variable a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z: std_logic;
   variable g1, g2, g3, g4, g5, g6, g7, g8, g9, g10: std_logic;

   begin

   -- Your test bench code

   testName := "16.41.0%.1        ";

   for tt in 0 to 2**16 loop
      tv := std_logic_vector(to_unsigned(tt,tv'Length));
      a := tv(0);
      b := tv(1);
      c := tv(2);
      d := tv(3);
      e := tv(4);
      f := tv(5);
      g := tv(6);
      h := tv(7);
      j := tv(8);
      k := tv(9);
      l := tv(10);
      m := tv(11);
      n := tv(12);
      p := tv(13);
      q := tv(14);
      r := tv(15);

		PS_MPLY_OR_DIV_OP_CODES <= a;
		PS_BODY_CTRL_LATCH <= b;
		PS_A_CYCLE_CTRL <= c;
		MS_EXTENSION_CTRL_LATCH <= not d;
		MS_BODY_CTRL_LATCH <= not e;
		MS_MQ_CTRL_LATCH <= not f;
		PS_UNITS_CTRL_LATCH <= g;
		MS_TABLE_SEARCH_A_CYCLE_U_CTRL <= not h;
		PS_B_CYCLE_CTRL <= j;
		PS_ARITH_TYPE_OP_CODES <= k;
		PS_C_CYCLE_CTRL <= l;
		PS_NO_SCAN_CTRL <= m;
		PS_MPLY_OP_CODE <= n;
		PS_NO_OR_1ST_OR_2ND_OR_3RD_SCAN_CTRL <= p;
		PS_D_CYCLE_CTRL <= q;
		PS_FILE_OP <= r;

      o := r and p and q;  -- Signal between pages
      g1 := l and m and n;
      
      wait for 30 ns;
      
      check1(MS_A_AR_RO_CTRL_STAR_ARITH,not(a and b and c),testName,"AAR RO CTRL");
      check1(MS_B_AR_RO_CTRL_STAR_ARITH,not((d or e or f) and k and j),testName,"BAR RO CTRL");
      check1(MS_MPLY_DOT_NO_SCAN_CTRL_DOT_C_CY_CTRL,not g1,testName,"MPLY.No Scan Ctrl.C Cy Ctrl");
      check1(PS_C_AR_RO_CTRL_STAR_ARITH,h or (a and g and c) or g1,testName,"CAR RO CTRL");
      check1(PS_D_AR_RO_CTRL_STAR_ARITH,o or (k and g and j) or (p and q and a),testName,"DAR RO CTRL");
      
   end loop;

   assert false report "Simulation Ended NORMALLY" severity failure;

   wait;
   end process;

-- The following is needed for older VHDL simulations to
-- terminate the simulation process.  If your environment
-- does not need it, it may be deleted.

stop_simulation: process
   begin
   wait for 2 ms;  -- Determines how long your simulation runs
   assert false report "Simulation Ended NORMALLY (TIMEOUT)" severity failure;
   end process;

-- END USER TEST BENCH PROCESS
   

END;
