-- VHDL for IBM SMS ALD page 12.30.04.1
-- Title: 2ND AND 3RD SCAN CTRLS
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 7/8/2020 2:54:13 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_12_30_04_1_2ND_AND_3RD_SCAN_CTRLS is
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MS_LOGIC_GATE_D_1:	 in STD_LOGIC;
		MS_DISPLAY_OR_ALTER_SET_2ND_SCAN:	 in STD_LOGIC;
		PS_NEXT_TO_LAST_LOGIC_GATE:	 in STD_LOGIC;
		PS_2ND_SCAN:	 in STD_LOGIC;
		PS_3RD_SCAN:	 in STD_LOGIC;
		PS_SET_2ND_SCAN_CTRL:	 in STD_LOGIC;
		PS_RGEN_2ND_SCAN_CTRL:	 in STD_LOGIC;
		PS_RGEN_3RD_SCAN_CTRL:	 in STD_LOGIC;
		PS_SET_3RD_SCAN_CTRL:	 in STD_LOGIC;
		MS_PROGRAM_RESET_1:	 in STD_LOGIC;
		PS_2ND_SCAN_CTRL:	 out STD_LOGIC;
		PS_3RD_SCAN_CTRL:	 out STD_LOGIC;
		MS_2ND_SCAN_CTRL:	 out STD_LOGIC;
		MS_3RD_SCAN_CTRL:	 out STD_LOGIC);
end ALD_12_30_04_1_2ND_AND_3RD_SCAN_CTRLS;

architecture behavioral of ALD_12_30_04_1_2ND_AND_3RD_SCAN_CTRLS is 

	signal OUT_3C_NoPin: STD_LOGIC;
	signal OUT_3C_NoPin_Latch: STD_LOGIC;
	signal OUT_2C_P: STD_LOGIC;
	signal OUT_2C_P_Latch: STD_LOGIC;
	signal OUT_1C_B: STD_LOGIC;
	signal OUT_4D_F: STD_LOGIC;
	signal OUT_2D_P: STD_LOGIC;
	signal OUT_4E_E: STD_LOGIC;
	signal OUT_1E_C: STD_LOGIC;
	signal OUT_3G_NoPin: STD_LOGIC;
	signal OUT_3G_NoPin_Latch: STD_LOGIC;
	signal OUT_2G_P: STD_LOGIC;
	signal OUT_2G_P_Latch: STD_LOGIC;
	signal OUT_1G_B: STD_LOGIC;
	signal OUT_4H_C: STD_LOGIC;
	signal OUT_4I_D: STD_LOGIC;
	signal OUT_1I_C: STD_LOGIC;
	signal OUT_DOT_2C: STD_LOGIC;

begin

	OUT_3C_NoPin_Latch <= NOT(MS_LOGIC_GATE_D_1 AND MS_PROGRAM_RESET_1 AND OUT_DOT_2C );
	OUT_2C_P_Latch <= NOT(OUT_4D_F AND OUT_4E_E AND OUT_3C_NoPin );
	OUT_1C_B <= NOT OUT_3C_NoPin;
	OUT_4D_F <= NOT(PS_NEXT_TO_LAST_LOGIC_GATE AND PS_SET_2ND_SCAN_CTRL );
	OUT_2D_P <= NOT(MS_DISPLAY_OR_ALTER_SET_2ND_SCAN );
	OUT_4E_E <= NOT(PS_NEXT_TO_LAST_LOGIC_GATE AND PS_2ND_SCAN AND PS_RGEN_2ND_SCAN_CTRL );
	OUT_1E_C <= NOT OUT_DOT_2C;
	OUT_3G_NoPin_Latch <= NOT(MS_LOGIC_GATE_D_1 AND MS_PROGRAM_RESET_1 AND OUT_2G_P );
	OUT_2G_P_Latch <= NOT(OUT_4H_C AND OUT_4I_D AND OUT_3G_NoPin );
	OUT_1G_B <= NOT OUT_3G_NoPin;
	OUT_4H_C <= NOT(PS_NEXT_TO_LAST_LOGIC_GATE AND PS_SET_3RD_SCAN_CTRL );
	OUT_4I_D <= NOT(PS_NEXT_TO_LAST_LOGIC_GATE AND PS_3RD_SCAN AND PS_RGEN_3RD_SCAN_CTRL );
	OUT_1I_C <= NOT OUT_2G_P;
	OUT_DOT_2C <= OUT_2D_P OR OUT_2C_P;

	PS_2ND_SCAN_CTRL <= OUT_1C_B;
	MS_2ND_SCAN_CTRL <= OUT_1E_C;
	PS_3RD_SCAN_CTRL <= OUT_1G_B;
	MS_3RD_SCAN_CTRL <= OUT_1I_C;

	Latch_3C: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_3C_NoPin_Latch,
		Q => OUT_3C_NoPin,
		QBar => OPEN );

	Latch_2C: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_2C_P_Latch,
		Q => OUT_2C_P,
		QBar => OPEN );

	Latch_3G: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_3G_NoPin_Latch,
		Q => OUT_3G_NoPin,
		QBar => OPEN );

	Latch_2G: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_2G_P_Latch,
		Q => OUT_2G_P,
		QBar => OPEN );


end;
