-- VHDL for IBM SMS ALD page 13.14.05.1
-- Title: OP CODE GROUPING-ACC
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 7/25/2020 11:23:37 AM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_13_14_05_1_OP_CODE_GROUPING_ACC is
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MS_SET_WORD_MARK_OP_CODE:	 in STD_LOGIC;
		MS_CLEAR_WORD_MARK_OP_CODE:	 in STD_LOGIC;
		MS_I_O_MOVE_OP_CODE:	 in STD_LOGIC;
		MS_I_O_LOAD_OP_CODE:	 in STD_LOGIC;
		MS_1401_STORE_A_AR_OP_CODE:	 in STD_LOGIC;
		MS_1401_STORE_B_AR_OP_CODE:	 in STD_LOGIC;
		MS_WORD_MARK_OP_CODES:	 out STD_LOGIC;
		PS_WORD_MARK_OP_CODES:	 out STD_LOGIC;
		MS_M_OR_L_OP_CODES:	 out STD_LOGIC;
		PS_M_OR_L_OP_CODES:	 out STD_LOGIC;
		MS_1401_STORE_AR_OP_CODES:	 out STD_LOGIC;
		PS_1401_STORE_AR_OP_CODES:	 out STD_LOGIC);
end ALD_13_14_05_1_OP_CODE_GROUPING_ACC;

architecture behavioral of ALD_13_14_05_1_OP_CODE_GROUPING_ACC is 

	signal OUT_5A_NoPin: STD_LOGIC;
	signal OUT_4A_R: STD_LOGIC;
	signal OUT_3B_F: STD_LOGIC;
	signal OUT_5C_NoPin: STD_LOGIC;
	signal OUT_4C_D: STD_LOGIC;
	signal OUT_3D_H: STD_LOGIC;
	signal OUT_5G_NoPin: STD_LOGIC;
	signal OUT_4G_R: STD_LOGIC;
	signal OUT_3H_H: STD_LOGIC;

begin

	OUT_5A_NoPin <= NOT(MS_SET_WORD_MARK_OP_CODE AND MS_CLEAR_WORD_MARK_OP_CODE );
	OUT_4A_R <= NOT OUT_5A_NoPin;
	OUT_3B_F <= NOT OUT_4A_R;
	OUT_5C_NoPin <= NOT(MS_I_O_MOVE_OP_CODE AND MS_I_O_LOAD_OP_CODE );
	OUT_4C_D <= NOT OUT_5C_NoPin;

	SMS_AEK_3D: entity SMS_AEK
	    port map (
		IN1 => OUT_4C_D,	-- Pin P
		OUT1 => OUT_3D_H,
		IN2 => OPEN );

	OUT_5G_NoPin <= NOT(MS_1401_STORE_A_AR_OP_CODE AND MS_1401_STORE_B_AR_OP_CODE );
	OUT_4G_R <= NOT OUT_5G_NoPin;

	SMS_AEK_3H: entity SMS_AEK
	    port map (
		IN1 => OUT_4G_R,	-- Pin P
		OUT1 => OUT_3H_H,
		IN2 => OPEN );


	MS_WORD_MARK_OP_CODES <= OUT_4A_R;
	PS_WORD_MARK_OP_CODES <= OUT_3B_F;
	MS_M_OR_L_OP_CODES <= OUT_4C_D;
	PS_M_OR_L_OP_CODES <= OUT_3D_H;
	MS_1401_STORE_AR_OP_CODES <= OUT_4G_R;
	PS_1401_STORE_AR_OP_CODES <= OUT_3H_H;


end;
