-- Test Bench VHDL for IBM SMS ALD page 11.10.33.1
-- Title: LOGIC GATE MIX
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 6/10/2020 7:37:21 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_11_10_33_1_LOGIC_GATE_MIX_tb is
end ALD_11_10_33_1_LOGIC_GATE_MIX_tb;

architecture behavioral of ALD_11_10_33_1_LOGIC_GATE_MIX_tb is

	-- Component Declaration for the Unit Under Test (UUT)

	component ALD_11_10_33_1_LOGIC_GATE_MIX
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MS_LOGIC_GATE_S:	 in STD_LOGIC;
		MS_LOGIC_GATE_T:	 in STD_LOGIC;
		MS_LOGIC_GATE_U:	 in STD_LOGIC;
		MS_LOGIC_GATE_V:	 in STD_LOGIC;
		MS_LOGIC_GATE_W:	 in STD_LOGIC;
		PS_LOGIC_GATE_S_OR_T:	 out STD_LOGIC;
		PS_LOGIC_GATE_U_OR_V_OR_W:	 out STD_LOGIC);
	end component;

	-- Inputs

	signal FPGA_CLK: STD_LOGIC := '0';
	signal MS_LOGIC_GATE_S: STD_LOGIC := '1';
	signal MS_LOGIC_GATE_T: STD_LOGIC := '1';
	signal MS_LOGIC_GATE_U: STD_LOGIC := '1';
	signal MS_LOGIC_GATE_V: STD_LOGIC := '1';
	signal MS_LOGIC_GATE_W: STD_LOGIC := '1';

	-- Outputs

	signal PS_LOGIC_GATE_S_OR_T: STD_LOGIC;
	signal PS_LOGIC_GATE_U_OR_V_OR_W: STD_LOGIC;

-- START USER TEST BENCH DECLARATIONS

-- The user test bench declarations, if any, must be
-- placed AFTER the line starts with the first line of text 
-- with -- START USER TEST BENCH DECLARATIONS and ends
-- with -- END USER TEST BENCH DECLARATIONS
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

   -- Your test bench declarations go here

-- END USER TEST BENCH DECLARATIONS
   

	begin

	-- Instantiate the Unit Under Test (UUT)

	UUT: ALD_11_10_33_1_LOGIC_GATE_MIX port map(
		FPGA_CLK => FPGA_CLK,
		MS_LOGIC_GATE_S => MS_LOGIC_GATE_S,
		MS_LOGIC_GATE_T => MS_LOGIC_GATE_T,
		MS_LOGIC_GATE_U => MS_LOGIC_GATE_U,
		MS_LOGIC_GATE_V => MS_LOGIC_GATE_V,
		MS_LOGIC_GATE_W => MS_LOGIC_GATE_W,
		PS_LOGIC_GATE_S_OR_T => PS_LOGIC_GATE_S_OR_T,
		PS_LOGIC_GATE_U_OR_V_OR_W => PS_LOGIC_GATE_U_OR_V_OR_W);

-- START USER TEST BENCH PROCESS

-- The user test bench code MUST be placed between the
-- line that starts with the first line of text that
-- begins with "-- START USERS TEST BENCH PROCESS" 
-- and ends with "-- END"
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

-- 
-- TestBenchFPGAClock.vhdl
--
-- Process to simulate the FPGA clock for a VHDL test bench
--

fpga_clk_process: process

   constant clk_period : time := 10 ns;

   begin
      fpga_clk <= '0';
      wait for clk_period / 2;
      fpga_clk <= '1';
      wait for clk_period / 2;
   end process;

--
-- End of TestBenchFPGAClock.vhdl
--   

-- Place your test bench code in the uut_process

uut_process: process
   begin

   -- Your test bench code

   wait;
   end process;

-- The following is needed for older VHDL simulations to
-- terminate the simulation process.  If your environment
-- does not need it, it may be deleted.

stop_simulation: process
   begin
   wait for 100 us;  -- Determines how long your simulation runs
   assert false report "Simulation Ended" severity failure;
   end process;

-- END USER TEST BENCH PROCESS
   

end;
