-- VHDL for IBM SMS ALD page 13.65.08.1
-- Title: 1401 ERROR LATCHES
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 8/7/2020 3:40:44 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_13_65_08_1_1401_ERROR_LATCHES is
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MS_PROGRAM_RESET_2:	 in STD_LOGIC;
		MS_RESET_INQUIRY_ERROR:	 in STD_LOGIC;
		MS_CONS_CANCEL_KEY_RESET:	 in STD_LOGIC;
		PS_CONSOLE_READ_OP:	 in STD_LOGIC;
		PS_A_CH_INVALID:	 in STD_LOGIC;
		PS_ERROR_SAMPLE:	 in STD_LOGIC;
		PS_CONSOLE_WRITE_OP:	 in STD_LOGIC;
		PS_CONS_DATA_CHECK:	 in STD_LOGIC;
		PS_E2_REG_FULL:	 in STD_LOGIC;
		PS_E_CH_STATUS_SAMPLE_B:	 in STD_LOGIC;
		PS_1401_INQUIRY_ERROR:	 out STD_LOGIC);
end ALD_13_65_08_1_1401_ERROR_LATCHES;

architecture behavioral of ALD_13_65_08_1_1401_ERROR_LATCHES is 

	signal OUT_4C_D: STD_LOGIC;
	signal OUT_4C_D_Latch: STD_LOGIC;
	signal OUT_3C_C: STD_LOGIC;
	signal OUT_3C_C_Latch: STD_LOGIC;
	signal OUT_5D_C: STD_LOGIC;
	signal OUT_5E_NoPin: STD_LOGIC;
	signal OUT_3E_F: STD_LOGIC;
	signal OUT_5F_NoPin: STD_LOGIC;
	signal OUT_DOT_2C: STD_LOGIC;

begin

	OUT_4C_D_Latch <= NOT(OUT_DOT_2C AND MS_PROGRAM_RESET_2 AND MS_RESET_INQUIRY_ERROR );
	OUT_3C_C_Latch <= NOT(OUT_4C_D AND MS_CONS_CANCEL_KEY_RESET AND OUT_5D_C );
	OUT_5D_C <= NOT(PS_CONSOLE_READ_OP AND PS_A_CH_INVALID AND PS_ERROR_SAMPLE );
	OUT_5E_NoPin <= NOT(PS_CONSOLE_WRITE_OP AND PS_CONS_DATA_CHECK );
	OUT_3E_F <= NOT(OUT_5E_NoPin AND OUT_5F_NoPin );
	OUT_5F_NoPin <= NOT(PS_E2_REG_FULL AND PS_E_CH_STATUS_SAMPLE_B );
	OUT_DOT_2C <= OUT_3C_C OR OUT_3E_F;

	PS_1401_INQUIRY_ERROR <= OUT_DOT_2C;

	Latch_4C: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_4C_D_Latch,
		Q => OUT_4C_D,
		QBar => OPEN );

	Latch_3C: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_3C_C_Latch,
		Q => OUT_3C_C,
		QBar => OPEN );


end;
