-- VHDL for IBM SMS ALD page 12.13.01.1
-- Title: I RING CONTROLS
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 7/2/2020 4:30:52 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_12_13_01_1_I_RING_CONTROLS is
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MS_LOGIC_GATE_E_1:	 in STD_LOGIC;
		PS_LOGIC_GATE_C_1:	 in STD_LOGIC;
		PS_I_RING_1_OR_6_TIME:	 in STD_LOGIC;
		PS_1401_MODE_1:	 in STD_LOGIC;
		PS_I_RING_1_TIME:	 in STD_LOGIC;
		PS_PERCENT_TYPE_OP_CODES:	 in STD_LOGIC;
		MS_PROGRAM_RESET_1:	 in STD_LOGIC;
		MS_LOGIC_GATE_D_1:	 in STD_LOGIC;
		MS_LAST_EX_DOT_NEXT_TO_LAST:	 in STD_LOGIC;
		MS_CONS_RESET_START_CONDITION:	 in STD_LOGIC;
		MS_I_O_LAST_EX_DOT_Z:	 in STD_LOGIC;
		MS_CONSOLE_SET_START_CND:	 in STD_LOGIC;
		MS_SET_I_RING_INTERRUPT:	 in STD_LOGIC;
		MS_SPL_ADV_CTRL_LAT:	 out STD_LOGIC;
		PS_I_RING_CTRL:	 out STD_LOGIC;
		MS_I_RING_CTRL:	 out STD_LOGIC);
end ALD_12_13_01_1_I_RING_CONTROLS;

architecture behavioral of ALD_12_13_01_1_I_RING_CONTROLS is 

	signal OUT_3B_G: STD_LOGIC;
	signal OUT_3B_G_Latch: STD_LOGIC;
	signal OUT_2B_G: STD_LOGIC;
	signal OUT_2B_G_Latch: STD_LOGIC;
	signal OUT_3C_E: STD_LOGIC;
	signal OUT_3D_G: STD_LOGIC;
	signal OUT_1E_B: STD_LOGIC;
	signal OUT_4F_NoPin: STD_LOGIC;
	signal OUT_4F_NoPin_Latch: STD_LOGIC;
	signal OUT_3F_P: STD_LOGIC;
	signal OUT_3F_P_Latch: STD_LOGIC;
	signal OUT_1F_C: STD_LOGIC;
	signal OUT_3H_C: STD_LOGIC;
	signal OUT_DOT_3F: STD_LOGIC;

begin

	OUT_3B_G_Latch <= NOT(MS_PROGRAM_RESET_1 AND OUT_2B_G AND MS_LOGIC_GATE_E_1 );
	OUT_2B_G_Latch <= NOT(OUT_3B_G AND OUT_3C_E AND OUT_3D_G );
	OUT_3C_E <= NOT(PS_I_RING_1_OR_6_TIME AND PS_1401_MODE_1 AND PS_LOGIC_GATE_C_1 );
	OUT_3D_G <= NOT(PS_PERCENT_TYPE_OP_CODES AND PS_LOGIC_GATE_C_1 AND PS_I_RING_1_TIME );
	OUT_1E_B <= NOT OUT_4F_NoPin;
	OUT_4F_NoPin_Latch <= NOT(OUT_DOT_3F AND MS_CONS_RESET_START_CONDITION AND MS_LOGIC_GATE_D_1 );
	OUT_3F_P_Latch <= NOT(OUT_4F_NoPin AND MS_PROGRAM_RESET_1 AND MS_LAST_EX_DOT_NEXT_TO_LAST );
	OUT_1F_C <= NOT OUT_DOT_3F;
	OUT_3H_C <= NOT(MS_CONSOLE_SET_START_CND AND MS_I_O_LAST_EX_DOT_Z AND MS_SET_I_RING_INTERRUPT );
	OUT_DOT_3F <= OUT_3F_P OR OUT_3H_C;

	MS_SPL_ADV_CTRL_LAT <= OUT_3B_G;
	PS_I_RING_CTRL <= OUT_1E_B;
	MS_I_RING_CTRL <= OUT_1F_C;

	Latch_3B: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_3B_G_Latch,
		Q => OUT_3B_G,
		QBar => OPEN );

	Latch_2B: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_2B_G_Latch,
		Q => OUT_2B_G,
		QBar => OPEN );

	Latch_4F: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_4F_NoPin_Latch,
		Q => OUT_4F_NoPin,
		QBar => OPEN );

	Latch_3F: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_3F_P_Latch,
		Q => OUT_3F_P,
		QBar => OPEN );


end;
