-- VHDL for IBM SMS ALD page 14.18.04.1
-- Title: ZONE ADDER 16K-ACC
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 11/7/2020 8:56:00 AM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;  -- For use in test benches only
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_14_18_04_1_ZONE_ADDER_16K_ACC is
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MS_ZONE_ADDER_A_A_DOT_B_A:	 in STD_LOGIC;
		PS_ZONE_ADDER_B_BITS_EVEN:	 in STD_LOGIC;
		PS_ZONE_ADDER_TWO_BIT:	 out STD_LOGIC;
		PS_ZONE_ADDER_NOT_TWO_BIT:	 out STD_LOGIC;
		PS_A_NOT_A_DOT_B_A_DOT_B_BITS_EVEN:	 out STD_LOGIC);
end ALD_14_18_04_1_ZONE_ADDER_16K_ACC;

architecture behavioral of ALD_14_18_04_1_ZONE_ADDER_16K_ACC is 

	signal OUT_4C_E: STD_LOGIC;
	signal OUT_3C_C: STD_LOGIC;
	signal OUT_5D_NoPin: STD_LOGIC;
	signal OUT_4D_NoPin: STD_LOGIC;
	signal OUT_5E_NoPin: STD_LOGIC;
	signal OUT_3E_A: STD_LOGIC;
	signal OUT_5F_F: STD_LOGIC;
	signal OUT_4F_NoPin: STD_LOGIC;
	signal OUT_5G_D: STD_LOGIC;

begin

	OUT_4C_E <= NOT(OUT_5D_NoPin AND OUT_4D_NoPin );
	OUT_3C_C <= NOT OUT_4C_E;
	OUT_5D_NoPin <= NOT(MS_ZONE_ADDER_A_A_DOT_B_A AND PS_ZONE_ADDER_B_BITS_EVEN );
	OUT_4D_NoPin <= NOT(OUT_5F_F AND OUT_5G_D );
	OUT_5E_NoPin <= NOT(OUT_5F_F AND OUT_5G_D );
	OUT_3E_A <= NOT(OUT_5E_NoPin AND OUT_4F_NoPin );
	OUT_5F_F <= NOT MS_ZONE_ADDER_A_A_DOT_B_A;
	OUT_4F_NoPin <= NOT(OUT_5F_F AND MS_ZONE_ADDER_A_A_DOT_B_A );
	OUT_5G_D <= NOT PS_ZONE_ADDER_B_BITS_EVEN;

	PS_ZONE_ADDER_NOT_TWO_BIT <= OUT_4C_E;
	PS_ZONE_ADDER_TWO_BIT <= OUT_3C_C;
	PS_A_NOT_A_DOT_B_A_DOT_B_BITS_EVEN <= OUT_3E_A;


end;
