-- Test Bench VHDL for IBM SMS ALD page 12.12.21.1
-- Title: B AND D CYCLE CTRL LATCHES
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 6/18/2020 8:35:05 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_12_12_21_1_B_AND_D_CYCLE_CTRL_LATCHES_tb is
end ALD_12_12_21_1_B_AND_D_CYCLE_CTRL_LATCHES_tb;

architecture behavioral of ALD_12_12_21_1_B_AND_D_CYCLE_CTRL_LATCHES_tb is

	-- Component Declaration for the Unit Under Test (UUT)

	component ALD_12_12_21_1_B_AND_D_CYCLE_CTRL_LATCHES
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MS_1401_I_O_SET_BRANCH_CNDS:	 in STD_LOGIC;
		PS_SET_B_CYCLE_CTRL:	 in STD_LOGIC;
		MS_LOGIC_GATE_D_1:	 in STD_LOGIC;
		MS_PROGRAM_RESET_1:	 in STD_LOGIC;
		PS_NEXT_TO_LAST_LOGIC_GATE:	 in STD_LOGIC;
		PS_SET_D_CYCLE_CTRL:	 in STD_LOGIC;
		MS_DISPLAY_ROUTINE:	 in STD_LOGIC;
		MS_ALTER_ROUTINE:	 in STD_LOGIC;
		PS_LOGIC_GATE_A_1:	 in STD_LOGIC;
		PS_CONSOLE_STROBE:	 in STD_LOGIC;
		PS_B_CYCLE_CTRL:	 out STD_LOGIC;
		MS_B_CYCLE_CTRL:	 out STD_LOGIC;
		PS_D_CYCLE_CTRL:	 out STD_LOGIC;
		MS_D_CYCLE_CTRL:	 out STD_LOGIC;
		MS_DISPLAY_OR_ALTER:	 out STD_LOGIC;
		PS_DISPLAY_OR_ALTER:	 out STD_LOGIC;
		MS_DISPLAY_OR_ALTER_SET_2ND_SCAN:	 out STD_LOGIC);
	end component;

	-- Inputs

	signal FPGA_CLK: STD_LOGIC := '0';
	signal MS_1401_I_O_SET_BRANCH_CNDS: STD_LOGIC := '1';
	signal PS_SET_B_CYCLE_CTRL: STD_LOGIC := '0';
	signal MS_LOGIC_GATE_D_1: STD_LOGIC := '1';
	signal MS_PROGRAM_RESET_1: STD_LOGIC := '1';
	signal PS_NEXT_TO_LAST_LOGIC_GATE: STD_LOGIC := '0';
	signal PS_SET_D_CYCLE_CTRL: STD_LOGIC := '0';
	signal MS_DISPLAY_ROUTINE: STD_LOGIC := '1';
	signal MS_ALTER_ROUTINE: STD_LOGIC := '1';
	signal PS_LOGIC_GATE_A_1: STD_LOGIC := '0';
	signal PS_CONSOLE_STROBE: STD_LOGIC := '0';

	-- Outputs

	signal PS_B_CYCLE_CTRL: STD_LOGIC;
	signal MS_B_CYCLE_CTRL: STD_LOGIC;
	signal PS_D_CYCLE_CTRL: STD_LOGIC;
	signal MS_D_CYCLE_CTRL: STD_LOGIC;
	signal MS_DISPLAY_OR_ALTER: STD_LOGIC;
	signal PS_DISPLAY_OR_ALTER: STD_LOGIC;
	signal MS_DISPLAY_OR_ALTER_SET_2ND_SCAN: STD_LOGIC;

-- START USER TEST BENCH DECLARATIONS

-- The user test bench declarations, if any, must be
-- placed AFTER the line starts with the first line of text 
-- with -- START USER TEST BENCH DECLARATIONS and ends
-- with the line containing -- END (and the rest of the line) below.
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

   -- Your test bench declarations go here

-- END USER TEST BENCH DECLARATIONS
   

	begin

	-- Instantiate the Unit Under Test (UUT)

	UUT: ALD_12_12_21_1_B_AND_D_CYCLE_CTRL_LATCHES port map(
		FPGA_CLK => FPGA_CLK,
		MS_1401_I_O_SET_BRANCH_CNDS => MS_1401_I_O_SET_BRANCH_CNDS,
		PS_SET_B_CYCLE_CTRL => PS_SET_B_CYCLE_CTRL,
		MS_LOGIC_GATE_D_1 => MS_LOGIC_GATE_D_1,
		MS_PROGRAM_RESET_1 => MS_PROGRAM_RESET_1,
		PS_NEXT_TO_LAST_LOGIC_GATE => PS_NEXT_TO_LAST_LOGIC_GATE,
		PS_SET_D_CYCLE_CTRL => PS_SET_D_CYCLE_CTRL,
		MS_DISPLAY_ROUTINE => MS_DISPLAY_ROUTINE,
		MS_ALTER_ROUTINE => MS_ALTER_ROUTINE,
		PS_LOGIC_GATE_A_1 => PS_LOGIC_GATE_A_1,
		PS_CONSOLE_STROBE => PS_CONSOLE_STROBE,
		PS_B_CYCLE_CTRL => PS_B_CYCLE_CTRL,
		MS_B_CYCLE_CTRL => MS_B_CYCLE_CTRL,
		PS_D_CYCLE_CTRL => PS_D_CYCLE_CTRL,
		MS_D_CYCLE_CTRL => MS_D_CYCLE_CTRL,
		MS_DISPLAY_OR_ALTER => MS_DISPLAY_OR_ALTER,
		PS_DISPLAY_OR_ALTER => PS_DISPLAY_OR_ALTER,
		MS_DISPLAY_OR_ALTER_SET_2ND_SCAN => MS_DISPLAY_OR_ALTER_SET_2ND_SCAN);

-- START USER TEST BENCH PROCESS

-- The user test bench code MUST be placed between the
-- line that starts with the first line of text that
-- begins with "-- START USERS TEST BENCH PROCESS" 
-- and ends with "-- END"
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

-- 
-- TestBenchFPGAClock.vhdl
--
-- Process to simulate the FPGA clock for a VHDL test bench
--

fpga_clk_process: process

   constant clk_period : time := 10 ns;

   begin
      fpga_clk <= '0';
      wait for clk_period / 2;
      fpga_clk <= '1';
      wait for clk_period / 2;
   end process;

--
-- End of TestBenchFPGAClock.vhdl
--   

-- Place your test bench code in the uut_process

uut_process: process
   begin

   -- Your test bench code

   wait;
   end process;

-- The following is needed for older VHDL simulations to
-- terminate the simulation process.  If your environment
-- does not need it, it may be deleted.

stop_simulation: process
   begin
   wait for 100 us;  -- Determines how long your simulation runs
   assert false report "Simulation Ended" severity failure;
   end process;

-- END USER TEST BENCH PROCESS
   

end;
