-- VHDL for IBM SMS ALD page 13.64.02.1
-- Title: F CH WORD SEPARATOR CONTROL
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 8/4/2020 2:04:52 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_13_64_02_1_F_CH_WORD_SEPARATOR_CONTROL is
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		PS_LOGIC_GATE_C_OR_D:	 in STD_LOGIC;
		PS_I_RING_4_TIME:	 in STD_LOGIC;
		PS_LOZENGE_OR_ASTERISK:	 in STD_LOGIC;
		MS_COMPUTER_RESET_1:	 in STD_LOGIC;
		PS_F_CH_RESET_STAR_1414:	 in STD_LOGIC;
		MS_F_CH_RESET:	 out STD_LOGIC;
		MS_F_CH_RESET_1:	 out STD_LOGIC;
		MS_F_CH_RESET_CORR_REC_LENGTH:	 out STD_LOGIC);
end ALD_13_64_02_1_F_CH_WORD_SEPARATOR_CONTROL;

architecture behavioral of ALD_13_64_02_1_F_CH_WORD_SEPARATOR_CONTROL is 

	signal OUT_3F_C: STD_LOGIC;
	signal OUT_5H_D: STD_LOGIC;
	signal OUT_4H_G: STD_LOGIC;
	signal OUT_3H_C: STD_LOGIC;
	signal OUT_DOT_4H: STD_LOGIC;

begin


	SMS_AEK_3F: entity SMS_AEK
	    port map (
		IN1 => OUT_DOT_4H,	-- Pin D
		OUT1 => OUT_3F_C,
		IN2 => OPEN );

	OUT_5H_D <= NOT(PS_LOGIC_GATE_C_OR_D AND PS_I_RING_4_TIME AND PS_LOZENGE_OR_ASTERISK );
	OUT_4H_G <= NOT(OUT_5H_D AND MS_COMPUTER_RESET_1 );
	OUT_3H_C <= OUT_3F_C;
	OUT_DOT_4H <= OUT_4H_G OR PS_F_CH_RESET_STAR_1414;

	MS_F_CH_RESET <= OUT_3F_C;
	MS_F_CH_RESET_CORR_REC_LENGTH <= OUT_5H_D;
	MS_F_CH_RESET_1 <= OUT_3H_C;


end;
