-- VHDL for IBM SMS ALD page 12.65.10.1
-- Title: 1401 MODE DRIVE-ACC
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 11/7/2020 1:25:10 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;  -- For use in test benches only
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_12_65_10_1_1401_MODE_DRIVE_ACC is
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MV_CONSOLE_PWR_SUPPLY_36_VOLTS:	 in STD_LOGIC;
		SWITCH_TOG_1401_MODE_PL1:	 in STD_LOGIC;
		PS_1401_MODE_1:	 out STD_LOGIC;
		MV_1401_MODE:	 out STD_LOGIC;
		PS_1401_MODE:	 out STD_LOGIC;
		LAMP_15A1K23:	 out STD_LOGIC);
end ALD_12_65_10_1_1401_MODE_DRIVE_ACC;

architecture behavioral of ALD_12_65_10_1_1401_MODE_DRIVE_ACC is 

	signal OUT_1A_C: STD_LOGIC;
	signal OUT_5B_T: STD_LOGIC;
	signal OUT_4B_F: STD_LOGIC;
	signal OUT_4C_A: STD_LOGIC;
	signal OUT_1F_H: STD_LOGIC;

begin


	SMS_AEK_1A: entity SMS_AEK
	    port map (
		IN1 => OUT_4B_F,	-- Pin D
		OUT1 => OUT_1A_C,
		IN2 => OPEN );

	OUT_5B_T <=  NOT SWITCH_TOG_1401_MODE_PL1;
	OUT_4B_F <= OUT_5B_T;
	OUT_4C_A <= OUT_5B_T;
	LAMP_15A1K23 <= OUT_4C_A;

	SMS_AEK_1F: entity SMS_AEK
	    port map (
		IN1 => OUT_4B_F,	-- Pin P
		OUT1 => OUT_1F_H,
		IN2 => OPEN );


	PS_1401_MODE_1 <= OUT_1A_C;
	MV_1401_MODE <= OUT_5B_T;
	PS_1401_MODE <= OUT_1F_H;


end;
