-- VHDL for IBM SMS ALD page 12.30.03.1
-- Title: NO SCAN AND 1ST SCAN CTRLS-ACC
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 7/8/2020 10:08:05 AM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_12_30_03_1_NO_SCAN_AND_1ST_SCAN_CTRLS_ACC is
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MS_1401_I_O_SET_BRANCH_CNDS:	 in STD_LOGIC;
		PS_NEXT_TO_LAST_LOGIC_GATE:	 in STD_LOGIC;
		PS_SET_NO_SCAN_CTRL:	 in STD_LOGIC;
		MS_LOGIC_GATE_D_1:	 in STD_LOGIC;
		MS_PROGRAM_RESET_1:	 in STD_LOGIC;
		PS_SET_1ST_SCAN_CTRL:	 in STD_LOGIC;
		PS_1ST_SCAN:	 in STD_LOGIC;
		PS_RGEN_1ST_SCAN_CTRL:	 in STD_LOGIC;
		MS_NO_SCAN_CTRL:	 out STD_LOGIC;
		PS_NO_SCAN_CTRL:	 out STD_LOGIC;
		PS_1ST_SCAN_CTRL:	 out STD_LOGIC;
		MS_1ST_SCAN_CTRL:	 out STD_LOGIC);
end ALD_12_30_03_1_NO_SCAN_AND_1ST_SCAN_CTRLS_ACC;

architecture behavioral of ALD_12_30_03_1_NO_SCAN_AND_1ST_SCAN_CTRLS_ACC is 

	signal OUT_3C_E: STD_LOGIC;
	signal OUT_3C_E_Latch: STD_LOGIC;
	signal OUT_2C_C: STD_LOGIC;
	signal OUT_2C_C_Latch: STD_LOGIC;
	signal OUT_1C_C: STD_LOGIC;
	signal OUT_4D_K: STD_LOGIC;
	signal OUT_2D_C: STD_LOGIC;
	signal OUT_1E_C: STD_LOGIC;
	signal OUT_3G_C: STD_LOGIC;
	signal OUT_3G_C_Latch: STD_LOGIC;
	signal OUT_2G_C: STD_LOGIC;
	signal OUT_2G_C_Latch: STD_LOGIC;
	signal OUT_4H_C: STD_LOGIC;
	signal OUT_1H_K: STD_LOGIC;
	signal OUT_4I_C: STD_LOGIC;

begin

	OUT_3C_E_Latch <= NOT(MS_LOGIC_GATE_D_1 AND MS_PROGRAM_RESET_1 AND OUT_2C_C );
	OUT_2C_C_Latch <= NOT(OUT_3C_E AND OUT_4D_K AND MS_1401_I_O_SET_BRANCH_CNDS );
	OUT_1C_C <= NOT OUT_2C_C;
	OUT_4D_K <= NOT(PS_NEXT_TO_LAST_LOGIC_GATE AND PS_SET_NO_SCAN_CTRL );
	OUT_2D_C <= NOT OUT_3C_E;
	OUT_1E_C <= NOT OUT_3G_C;
	OUT_3G_C_Latch <= NOT(MS_LOGIC_GATE_D_1 AND MS_PROGRAM_RESET_1 AND OUT_2G_C );
	OUT_2G_C_Latch <= NOT(OUT_3G_C AND OUT_4H_C AND OUT_4I_C );
	OUT_4H_C <= NOT(PS_NEXT_TO_LAST_LOGIC_GATE AND PS_SET_1ST_SCAN_CTRL );
	OUT_1H_K <= NOT OUT_2G_C;
	OUT_4I_C <= NOT(PS_NEXT_TO_LAST_LOGIC_GATE AND PS_RGEN_1ST_SCAN_CTRL AND PS_1ST_SCAN );

	MS_NO_SCAN_CTRL <= OUT_1C_C;
	PS_NO_SCAN_CTRL <= OUT_2D_C;
	PS_1ST_SCAN_CTRL <= OUT_1E_C;
	MS_1ST_SCAN_CTRL <= OUT_1H_K;

	Latch_3C: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_3C_E_Latch,
		Q => OUT_3C_E,
		QBar => OPEN );

	Latch_2C: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_2C_C_Latch,
		Q => OUT_2C_C,
		QBar => OPEN );

	Latch_3G: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_3G_C_Latch,
		Q => OUT_3G_C,
		QBar => OPEN );

	Latch_2G: entity DFlipFlop port map (
		C => FPGA_CLK,
		D => OUT_2G_C_Latch,
		Q => OUT_2G_C,
		QBar => OPEN );


end;
