-- Test Bench VHDL for IBM SMS ALD page 41.30.01.1
-- Title: CONSOLE INQUIRY REQUEST
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 10/24/2020 5:49:58 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;  -- For use in test benches only
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_41_30_01_1_CONSOLE_INQUIRY_REQUEST_tb is
end ALD_41_30_01_1_CONSOLE_INQUIRY_REQUEST_tb;

architecture behavioral of ALD_41_30_01_1_CONSOLE_INQUIRY_REQUEST_tb is

	-- Component Declaration for the Unit Under Test (UUT)

	component ALD_41_30_01_1_CONSOLE_INQUIRY_REQUEST
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		PS_CONS_RELEASE_OR_CANCEL:	 in STD_LOGIC;
		MS_LAST_INSN_RO_CYCLE:	 in STD_LOGIC;
		MS_PROGRAM_RESET_4:	 in STD_LOGIC;
		MV_CONS_INQUIRY_REQUEST_KEY_STAR_NO:	 in STD_LOGIC;
		MS_CONS_INQUIRY_REQUEST:	 out STD_LOGIC);
	end component;

	-- Inputs

	signal FPGA_CLK: STD_LOGIC := '0';
	signal PS_CONS_RELEASE_OR_CANCEL: STD_LOGIC := '0';
	signal MS_LAST_INSN_RO_CYCLE: STD_LOGIC := '1';
	signal MS_PROGRAM_RESET_4: STD_LOGIC := '1';
	signal MV_CONS_INQUIRY_REQUEST_KEY_STAR_NO: STD_LOGIC := '1';

	-- Outputs

	signal MS_CONS_INQUIRY_REQUEST: STD_LOGIC;

-- START USER TEST BENCH DECLARATIONS

-- The user test bench declarations, if any, must be
-- placed AFTER the line starts with the first line of text 
-- with -- START USER TEST BENCH DECLARATIONS and ends
-- with the line containing -- END (and the rest of the line) below.
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

   constant HDL_C_BIT: integer := 7;
   constant HDL_WM_BIT: integer := 6;
   constant HDL_B_BIT: integer := 5;
   constant HDL_A_BIT: integer := 4;
   constant HDL_8_BIT: integer := 3;
   constant HDL_4_BIT: integer := 2;
   constant HDL_2_BIT: integer := 1;
   constant HDL_1_BIT: integer := 0;

   constant MX_X1A_POS: integer := 7;
   constant MX_X6A_POS: integer := 8;

procedure check1(
    checked: in STD_LOGIC;
    val: in STD_LOGIC;
    testname: in string;
    test: in string) is
    begin    
    assert checked = val report testname & " (" & test & ") failed." severity failure;
    end procedure;
      


   -- Your test bench declarations go here

-- END USER TEST BENCH DECLARATIONS
   

	begin

	-- Instantiate the Unit Under Test (UUT)

	UUT: ALD_41_30_01_1_CONSOLE_INQUIRY_REQUEST port map(
		FPGA_CLK => FPGA_CLK,
		PS_CONS_RELEASE_OR_CANCEL => PS_CONS_RELEASE_OR_CANCEL,
		MS_LAST_INSN_RO_CYCLE => MS_LAST_INSN_RO_CYCLE,
		MS_PROGRAM_RESET_4 => MS_PROGRAM_RESET_4,
		MV_CONS_INQUIRY_REQUEST_KEY_STAR_NO => MV_CONS_INQUIRY_REQUEST_KEY_STAR_NO,
		MS_CONS_INQUIRY_REQUEST => MS_CONS_INQUIRY_REQUEST);

-- START USER TEST BENCH PROCESS

-- The user test bench code MUST be placed between the
-- line that starts with the first line of text that
-- begins with "-- START USERS TEST BENCH PROCESS" 
-- and ends with "-- END"
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

-- 
-- TestBenchFPGAClock.vhdl
--
-- Process to simulate the FPGA clock for a VHDL test bench
--

fpga_clk_process: process

   constant clk_period : time := 10 ns;

   begin
      fpga_clk <= '0';
      wait for clk_period / 2;
      fpga_clk <= '1';
      wait for clk_period / 2;
   end process;

--
-- End of TestBenchFPGAClock.vhdl
--   

-- Place your test bench code in the uut_process

uut_process: process

   variable testName: string(1 to 18);
   variable subtest: integer;
   variable tv: std_logic_vector(25 downto 0);
   variable a,b,c,d,e,f,g,h,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z: std_logic;
   variable g1, g2, g3, g4, g5, g6, g7, g8, g9, g10: std_logic;

   begin

   -- Your test bench code

   testName := "41.30.01.1        ";

   for tt in 0 to 2**3 loop
      tv := std_logic_vector(to_unsigned(tt,tv'Length));
      a := tv(0);
      b := tv(1);
      d := tv(2);
      
      -- Reset the latch
      
      MS_PROGRAM_RESET_4 <= '0';
      wait for 30 ns;
      MS_PROGRAM_RESET_4 <= '1';
      wait for 30 ns;

      check1(MS_CONS_INQUIRY_REQUEST,'1',testName,"Loop Reset Inquiry Request");

      -- Maybe set the latch

		MV_CONS_INQUIRY_REQUEST_KEY_STAR_NO <= not d;
		wait for 30 ns; -- Latch sets - maybe
		MV_CONS_INQUIRY_REQUEST_KEY_STAR_NO <= '1';
      wait for 30 ns; -- Latch should not change

      check1(MS_CONS_INQUIRY_REQUEST,not d,testName,"Inquiry Request Set");
      
      -- Maybe reset the latch

		PS_CONS_RELEASE_OR_CANCEL <= a;
		MS_LAST_INSN_RO_CYCLE <= not b;
		wait for 30 ns; -- Latch resets - maybe
		
		PS_CONS_RELEASE_OR_CANCEL <= '0';
      MS_LAST_INSN_RO_CYCLE <= '1';
      wait for 30 ns; -- latch should not change

      check1(MS_CONS_INQUIRY_REQUEST,not(d and not(a and not b)),testName,"Inquiry Request Reset");
      
      
   end loop;

   assert false report "Simulation Ended NORMALLY" severity failure;

   wait;
   end process;

-- The following is needed for older VHDL simulations to
-- terminate the simulation process.  If your environment
-- does not need it, it may be deleted.

stop_simulation: process
   begin
   wait for 2 ms;  -- Determines how long your simulation runs
   assert false report "Simulation Ended NORMALLY (TIMEOUT)" severity failure;
   end process;

-- END USER TEST BENCH PROCESS
   

end;
