-- Test Bench VHDL for IBM SMS ALD page 14.71.20.1
-- Title: A AR RESET
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 9/5/2020 3:16:37 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;  -- For use in test benches only
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_14_71_20_1_A_AR_RESET_tb is
end ALD_14_71_20_1_A_AR_RESET_tb;

architecture behavioral of ALD_14_71_20_1_A_AR_RESET_tb is

	-- Component Declaration for the Unit Under Test (UUT)

	component ALD_14_71_20_1_A_AR_RESET
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MS_SYSTEM_RESET:	 in STD_LOGIC;
		PS_A_CYCLE_CTRL:	 in STD_LOGIC;
		PS_LOGIC_GATE_EARLY_B:	 in STD_LOGIC;
		PS_1311_RESET_AAR:	 in STD_LOGIC;
		PS_INDEX_A_AR:	 in STD_LOGIC;
		PS_A_RING_2_TIME:	 in STD_LOGIC;
		PS_LOGIC_GATE_EARLY_F:	 in STD_LOGIC;
		PS_I_RING_1_OR_1401_AND_3_TIME:	 in STD_LOGIC;
		PS_A_CH_NOT_WM_BIT:	 in STD_LOGIC;
		PS_1ST_CLOCK_PULSE_1:	 in STD_LOGIC;
		PS_PERCENT_TYPE_OP_CODES:	 in STD_LOGIC;
		MS_STORE_ADDR_REGS_OP_CODE:	 in STD_LOGIC;
		PS_SET_A_AR:	 in STD_LOGIC;
		PS_CONSOLE_CYCLE_START:	 in STD_LOGIC;
		PS_2_CHAR_ONLY_OP_CODES:	 in STD_LOGIC;
		MS_1401_MODE_1:	 in STD_LOGIC;
		MS_RESET_A_AR:	 out STD_LOGIC;
		MS_INDEX_A_AR_DOT_A_RING_2_TIME:	 out STD_LOGIC;
		MS_RESET_C_AR_1:	 out STD_LOGIC);
	end component;

	-- Inputs

	signal FPGA_CLK: STD_LOGIC := '0';
	signal MS_SYSTEM_RESET: STD_LOGIC := '1';
	signal PS_A_CYCLE_CTRL: STD_LOGIC := '0';
	signal PS_LOGIC_GATE_EARLY_B: STD_LOGIC := '0';
	signal PS_1311_RESET_AAR: STD_LOGIC := '0';
	signal PS_INDEX_A_AR: STD_LOGIC := '0';
	signal PS_A_RING_2_TIME: STD_LOGIC := '0';
	signal PS_LOGIC_GATE_EARLY_F: STD_LOGIC := '0';
	signal PS_I_RING_1_OR_1401_AND_3_TIME: STD_LOGIC := '0';
	signal PS_A_CH_NOT_WM_BIT: STD_LOGIC := '0';
	signal PS_1ST_CLOCK_PULSE_1: STD_LOGIC := '0';
	signal PS_PERCENT_TYPE_OP_CODES: STD_LOGIC := '0';
	signal MS_STORE_ADDR_REGS_OP_CODE: STD_LOGIC := '1';
	signal PS_SET_A_AR: STD_LOGIC := '0';
	signal PS_CONSOLE_CYCLE_START: STD_LOGIC := '0';
	signal PS_2_CHAR_ONLY_OP_CODES: STD_LOGIC := '0';
	signal MS_1401_MODE_1: STD_LOGIC := '1';

	-- Outputs

	signal MS_RESET_A_AR: STD_LOGIC;
	signal MS_INDEX_A_AR_DOT_A_RING_2_TIME: STD_LOGIC;
	signal MS_RESET_C_AR_1: STD_LOGIC;

-- START USER TEST BENCH DECLARATIONS

-- The user test bench declarations, if any, must be
-- placed AFTER the line starts with the first line of text 
-- with -- START USER TEST BENCH DECLARATIONS and ends
-- with the line containing -- END (and the rest of the line) below.
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

   constant HDL_C_BIT: integer := 7;
   constant HDL_WM_BIT: integer := 6;
   constant HDL_B_BIT: integer := 5;
   constant HDL_A_BIT: integer := 4;
   constant HDL_8_BIT: integer := 3;
   constant HDL_4_BIT: integer := 2;
   constant HDL_2_BIT: integer := 1;
   constant HDL_1_BIT: integer := 0;

procedure check1(
    checked: in STD_LOGIC;
    val: in STD_LOGIC;
    testname: in string;
    test: in string) is
    begin    
    assert checked = val report testname & " (" & test & ") failed." severity failure;
    end procedure;
      


   -- Your test bench declarations go here

-- END USER TEST BENCH DECLARATIONS
   

	begin

	-- Instantiate the Unit Under Test (UUT)

	UUT: ALD_14_71_20_1_A_AR_RESET port map(
		FPGA_CLK => FPGA_CLK,
		MS_SYSTEM_RESET => MS_SYSTEM_RESET,
		PS_A_CYCLE_CTRL => PS_A_CYCLE_CTRL,
		PS_LOGIC_GATE_EARLY_B => PS_LOGIC_GATE_EARLY_B,
		PS_1311_RESET_AAR => PS_1311_RESET_AAR,
		PS_INDEX_A_AR => PS_INDEX_A_AR,
		PS_A_RING_2_TIME => PS_A_RING_2_TIME,
		PS_LOGIC_GATE_EARLY_F => PS_LOGIC_GATE_EARLY_F,
		PS_I_RING_1_OR_1401_AND_3_TIME => PS_I_RING_1_OR_1401_AND_3_TIME,
		PS_A_CH_NOT_WM_BIT => PS_A_CH_NOT_WM_BIT,
		PS_1ST_CLOCK_PULSE_1 => PS_1ST_CLOCK_PULSE_1,
		PS_PERCENT_TYPE_OP_CODES => PS_PERCENT_TYPE_OP_CODES,
		MS_STORE_ADDR_REGS_OP_CODE => MS_STORE_ADDR_REGS_OP_CODE,
		PS_SET_A_AR => PS_SET_A_AR,
		PS_CONSOLE_CYCLE_START => PS_CONSOLE_CYCLE_START,
		PS_2_CHAR_ONLY_OP_CODES => PS_2_CHAR_ONLY_OP_CODES,
		MS_1401_MODE_1 => MS_1401_MODE_1,
		MS_RESET_A_AR => MS_RESET_A_AR,
		MS_INDEX_A_AR_DOT_A_RING_2_TIME => MS_INDEX_A_AR_DOT_A_RING_2_TIME,
		MS_RESET_C_AR_1 => MS_RESET_C_AR_1);

-- START USER TEST BENCH PROCESS

-- The user test bench code MUST be placed between the
-- line that starts with the first line of text that
-- begins with "-- START USERS TEST BENCH PROCESS" 
-- and ends with "-- END"
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

-- 
-- TestBenchFPGAClock.vhdl
--
-- Process to simulate the FPGA clock for a VHDL test bench
--

fpga_clk_process: process

   constant clk_period : time := 10 ns;

   begin
      fpga_clk <= '0';
      wait for clk_period / 2;
      fpga_clk <= '1';
      wait for clk_period / 2;
   end process;

--
-- End of TestBenchFPGAClock.vhdl
--   

-- Place your test bench code in the uut_process

uut_process: process

   variable testName: string(1 to 18);
   variable subtest: integer;
   variable tv: std_logic_vector(15 downto 0);
   variable a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p: std_logic;
   variable g1, g2, g3, g4, g5, g6: std_logic;

   begin

   -- Your test bench code

   assert false report "Simulation Ended NORMALLY" severity failure;

   wait;
   end process;

-- The following is needed for older VHDL simulations to
-- terminate the simulation process.  If your environment
-- does not need it, it may be deleted.

stop_simulation: process
   begin
   wait for 2 ms;  -- Determines how long your simulation runs
   assert false report "Simulation Ended NORMALLY (TIMEOUT)" severity failure;
   end process;

-- END USER TEST BENCH PROCESS
   

end;
