-- Test Bench VHDL for IBM SMS ALD page 14.30.03.1
-- Title: ADDRESS MODIFICATION
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 8/28/2020 10:42:52 AM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_14_30_03_1_ADDRESS_MODIFICATION_tb is
end ALD_14_30_03_1_ADDRESS_MODIFICATION_tb;

architecture behavioral of ALD_14_30_03_1_ADDRESS_MODIFICATION_tb is

	-- Component Declaration for the Unit Under Test (UUT)

	component ALD_14_30_03_1_ADDRESS_MODIFICATION
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		PY_MEM_AR_TTHP0B_TO_MOD:	 in STD_LOGIC;
		PY_MEM_AR_THP0B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_HP0B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_TP0B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_UP0B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_TTHP1B_TO_MOD:	 in STD_LOGIC;
		PY_MEM_AR_THP1B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_HP1B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_TP1B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_UP1B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_TTHP2B_TO_MOD:	 in STD_LOGIC;
		PY_MEM_AR_THP2B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_HP2B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_TP2B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_UP2B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_TTHP4B_TO_MOD:	 in STD_LOGIC;
		PY_MEM_AR_THP4B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_HP4B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_TP4B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_UP4B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_TTHP8B_TO_MOD:	 in STD_LOGIC;
		PY_MEM_AR_THP8B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_HP8B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_TP8B_TO_ADDR_MOD:	 in STD_LOGIC;
		PY_MEM_AR_UP8B_TO_ADDR_MOD:	 in STD_LOGIC;
		MY_MEM_AR_TO_ADDR_MOD_0_BIT:	 out STD_LOGIC;
		MY_MEM_AR_TO_ADDR_MOD_1_BIT:	 out STD_LOGIC;
		MY_MEM_AR_TO_ADDR_MOD_2_BIT:	 out STD_LOGIC;
		MY_MEM_AR_TO_ADDR_MOD_4_BIT:	 out STD_LOGIC;
		MY_MEM_AR_TO_ADDR_MOD_8_BIT:	 out STD_LOGIC);
	end component;

	-- Inputs

	signal FPGA_CLK: STD_LOGIC := '0';
	signal PY_MEM_AR_TTHP0B_TO_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_THP0B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_HP0B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_TP0B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_UP0B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_TTHP1B_TO_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_THP1B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_HP1B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_TP1B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_UP1B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_TTHP2B_TO_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_THP2B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_HP2B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_TP2B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_UP2B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_TTHP4B_TO_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_THP4B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_HP4B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_TP4B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_UP4B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_TTHP8B_TO_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_THP8B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_HP8B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_TP8B_TO_ADDR_MOD: STD_LOGIC := '0';
	signal PY_MEM_AR_UP8B_TO_ADDR_MOD: STD_LOGIC := '0';

	-- Outputs

	signal MY_MEM_AR_TO_ADDR_MOD_0_BIT: STD_LOGIC;
	signal MY_MEM_AR_TO_ADDR_MOD_1_BIT: STD_LOGIC;
	signal MY_MEM_AR_TO_ADDR_MOD_2_BIT: STD_LOGIC;
	signal MY_MEM_AR_TO_ADDR_MOD_4_BIT: STD_LOGIC;
	signal MY_MEM_AR_TO_ADDR_MOD_8_BIT: STD_LOGIC;

-- START USER TEST BENCH DECLARATIONS

-- The user test bench declarations, if any, must be
-- placed AFTER the line starts with the first line of text 
-- with -- START USER TEST BENCH DECLARATIONS and ends
-- with the line containing -- END (and the rest of the line) below.
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

   constant HDL_C_BIT: integer := 7;
   constant HDL_WM_BIT: integer := 6;
   constant HDL_B_BIT: integer := 5;
   constant HDL_A_BIT: integer := 4;
   constant HDL_8_BIT: integer := 3;
   constant HDL_4_BIT: integer := 2;
   constant HDL_2_BIT: integer := 1;
   constant HDL_1_BIT: integer := 0;

procedure check1(
    checked: in STD_LOGIC;
    val: in STD_LOGIC;
    testname: in string;
    test: in string) is
    begin    
    assert checked = val report testname & " (" & test & ") failed." severity failure;
    end procedure;
      


   -- Your test bench declarations go here

-- END USER TEST BENCH DECLARATIONS
   

	begin

	-- Instantiate the Unit Under Test (UUT)

	UUT: ALD_14_30_03_1_ADDRESS_MODIFICATION port map(
		FPGA_CLK => FPGA_CLK,
		PY_MEM_AR_TTHP0B_TO_MOD => PY_MEM_AR_TTHP0B_TO_MOD,
		PY_MEM_AR_THP0B_TO_ADDR_MOD => PY_MEM_AR_THP0B_TO_ADDR_MOD,
		PY_MEM_AR_HP0B_TO_ADDR_MOD => PY_MEM_AR_HP0B_TO_ADDR_MOD,
		PY_MEM_AR_TP0B_TO_ADDR_MOD => PY_MEM_AR_TP0B_TO_ADDR_MOD,
		PY_MEM_AR_UP0B_TO_ADDR_MOD => PY_MEM_AR_UP0B_TO_ADDR_MOD,
		PY_MEM_AR_TTHP1B_TO_MOD => PY_MEM_AR_TTHP1B_TO_MOD,
		PY_MEM_AR_THP1B_TO_ADDR_MOD => PY_MEM_AR_THP1B_TO_ADDR_MOD,
		PY_MEM_AR_HP1B_TO_ADDR_MOD => PY_MEM_AR_HP1B_TO_ADDR_MOD,
		PY_MEM_AR_TP1B_TO_ADDR_MOD => PY_MEM_AR_TP1B_TO_ADDR_MOD,
		PY_MEM_AR_UP1B_TO_ADDR_MOD => PY_MEM_AR_UP1B_TO_ADDR_MOD,
		PY_MEM_AR_TTHP2B_TO_MOD => PY_MEM_AR_TTHP2B_TO_MOD,
		PY_MEM_AR_THP2B_TO_ADDR_MOD => PY_MEM_AR_THP2B_TO_ADDR_MOD,
		PY_MEM_AR_HP2B_TO_ADDR_MOD => PY_MEM_AR_HP2B_TO_ADDR_MOD,
		PY_MEM_AR_TP2B_TO_ADDR_MOD => PY_MEM_AR_TP2B_TO_ADDR_MOD,
		PY_MEM_AR_UP2B_TO_ADDR_MOD => PY_MEM_AR_UP2B_TO_ADDR_MOD,
		PY_MEM_AR_TTHP4B_TO_MOD => PY_MEM_AR_TTHP4B_TO_MOD,
		PY_MEM_AR_THP4B_TO_ADDR_MOD => PY_MEM_AR_THP4B_TO_ADDR_MOD,
		PY_MEM_AR_HP4B_TO_ADDR_MOD => PY_MEM_AR_HP4B_TO_ADDR_MOD,
		PY_MEM_AR_TP4B_TO_ADDR_MOD => PY_MEM_AR_TP4B_TO_ADDR_MOD,
		PY_MEM_AR_UP4B_TO_ADDR_MOD => PY_MEM_AR_UP4B_TO_ADDR_MOD,
		PY_MEM_AR_TTHP8B_TO_MOD => PY_MEM_AR_TTHP8B_TO_MOD,
		PY_MEM_AR_THP8B_TO_ADDR_MOD => PY_MEM_AR_THP8B_TO_ADDR_MOD,
		PY_MEM_AR_HP8B_TO_ADDR_MOD => PY_MEM_AR_HP8B_TO_ADDR_MOD,
		PY_MEM_AR_TP8B_TO_ADDR_MOD => PY_MEM_AR_TP8B_TO_ADDR_MOD,
		PY_MEM_AR_UP8B_TO_ADDR_MOD => PY_MEM_AR_UP8B_TO_ADDR_MOD,
		MY_MEM_AR_TO_ADDR_MOD_0_BIT => MY_MEM_AR_TO_ADDR_MOD_0_BIT,
		MY_MEM_AR_TO_ADDR_MOD_1_BIT => MY_MEM_AR_TO_ADDR_MOD_1_BIT,
		MY_MEM_AR_TO_ADDR_MOD_2_BIT => MY_MEM_AR_TO_ADDR_MOD_2_BIT,
		MY_MEM_AR_TO_ADDR_MOD_4_BIT => MY_MEM_AR_TO_ADDR_MOD_4_BIT,
		MY_MEM_AR_TO_ADDR_MOD_8_BIT => MY_MEM_AR_TO_ADDR_MOD_8_BIT);

-- START USER TEST BENCH PROCESS

-- The user test bench code MUST be placed between the
-- line that starts with the first line of text that
-- begins with "-- START USERS TEST BENCH PROCESS" 
-- and ends with "-- END"
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

-- 
-- TestBenchFPGAClock.vhdl
--
-- Process to simulate the FPGA clock for a VHDL test bench
--

fpga_clk_process: process

   constant clk_period : time := 10 ns;

   begin
      fpga_clk <= '0';
      wait for clk_period / 2;
      fpga_clk <= '1';
      wait for clk_period / 2;
   end process;

--
-- End of TestBenchFPGAClock.vhdl
--   

-- Place your test bench code in the uut_process

uut_process: process

   variable testName: string(1 to 18);
   variable subtest: integer;

   begin

   -- Your test bench code

   wait;
   end process;

-- The following is needed for older VHDL simulations to
-- terminate the simulation process.  If your environment
-- does not need it, it may be deleted.

stop_simulation: process
   begin
   wait for 100 us;  -- Determines how long your simulation runs
   assert false report "Simulation Ended NORMALLY" severity failure;
   end process;

-- END USER TEST BENCH PROCESS
   

end;
