-- Test Bench VHDL for IBM SMS ALD page 14.15.23.1
-- Title: REAL TIME CLOCK CONTROLS
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 8/20/2020 5:22:58 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_14_15_23_1_REAL_TIME_CLOCK_CONTROLS_tb is
end ALD_14_15_23_1_REAL_TIME_CLOCK_CONTROLS_tb;

architecture behavioral of ALD_14_15_23_1_REAL_TIME_CLOCK_CONTROLS_tb is

	-- Component Declaration for the Unit Under Test (UUT)

	component ALD_14_15_23_1_REAL_TIME_CLOCK_CONTROLS
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		PS_T_SYMBOL_OP_MODIFIER:	 in STD_LOGIC;
		PS_C_CYCLE:	 in STD_LOGIC;
		MS_REAL_TIME_CLOCK_0_DIGIT:	 in STD_LOGIC;
		MS_REAL_TIME_CLOCK_1_DIGIT:	 in STD_LOGIC;
		MS_REAL_TIME_CLOCK_2_DIGIT:	 in STD_LOGIC;
		MS_REAL_TIME_CLOCK_3_DIGIT:	 in STD_LOGIC;
		MS_REAL_TIME_CLOCK_4_DIGIT:	 in STD_LOGIC;
		MS_REAL_TIME_CLOCK_5_DIGIT:	 in STD_LOGIC;
		MS_REAL_TIME_CLOCK_6_DIGIT:	 in STD_LOGIC;
		MS_REAL_TIME_CLOCK_7_DIGIT:	 in STD_LOGIC;
		MS_REAL_TIME_CLOCK_8_DIGIT:	 in STD_LOGIC;
		PS_STORE_ADDR_REGS_OP_CODE:	 in STD_LOGIC;
		MS_REAL_TIME_CLOCK_9_DIGIT:	 in STD_LOGIC;
		MS_A_RING_6_TIME:	 in STD_LOGIC;
		PS_LOGIC_GATE_C_1:	 in STD_LOGIC;
		PS_I_RING_7_TIME:	 in STD_LOGIC;
		PS_I_CYCLE:	 in STD_LOGIC;
		PS_LOGIC_GATE_F_1:	 in STD_LOGIC;
		MS_I_RING_6_TIME:	 in STD_LOGIC;
		MV_36_VOLTS:	 in STD_LOGIC;
		SWITCH_REL_RTC_BUSY:	 in STD_LOGIC;
		MS_STORE_ADDR_REGS_OP_DOT_T_DOT_C_CY:	 out STD_LOGIC;
		PS_STORE_ADDR_REGS_OP_DOT_T_DOT_C_CY:	 out STD_LOGIC;
		PS_RTC_BUSY:	 out STD_LOGIC;
		MS_RTC_BUSY:	 out STD_LOGIC);
	end component;

	-- Inputs

	signal FPGA_CLK: STD_LOGIC := '0';
	signal PS_T_SYMBOL_OP_MODIFIER: STD_LOGIC := '0';
	signal PS_C_CYCLE: STD_LOGIC := '0';
	signal MS_REAL_TIME_CLOCK_0_DIGIT: STD_LOGIC := '1';
	signal MS_REAL_TIME_CLOCK_1_DIGIT: STD_LOGIC := '1';
	signal MS_REAL_TIME_CLOCK_2_DIGIT: STD_LOGIC := '1';
	signal MS_REAL_TIME_CLOCK_3_DIGIT: STD_LOGIC := '1';
	signal MS_REAL_TIME_CLOCK_4_DIGIT: STD_LOGIC := '1';
	signal MS_REAL_TIME_CLOCK_5_DIGIT: STD_LOGIC := '1';
	signal MS_REAL_TIME_CLOCK_6_DIGIT: STD_LOGIC := '1';
	signal MS_REAL_TIME_CLOCK_7_DIGIT: STD_LOGIC := '1';
	signal MS_REAL_TIME_CLOCK_8_DIGIT: STD_LOGIC := '1';
	signal PS_STORE_ADDR_REGS_OP_CODE: STD_LOGIC := '0';
	signal MS_REAL_TIME_CLOCK_9_DIGIT: STD_LOGIC := '1';
	signal MS_A_RING_6_TIME: STD_LOGIC := '1';
	signal PS_LOGIC_GATE_C_1: STD_LOGIC := '0';
	signal PS_I_RING_7_TIME: STD_LOGIC := '0';
	signal PS_I_CYCLE: STD_LOGIC := '0';
	signal PS_LOGIC_GATE_F_1: STD_LOGIC := '0';
	signal MS_I_RING_6_TIME: STD_LOGIC := '1';
	signal MV_36_VOLTS: STD_LOGIC := '1';
	signal SWITCH_REL_RTC_BUSY: STD_LOGIC := '0';

	-- Outputs

	signal MS_STORE_ADDR_REGS_OP_DOT_T_DOT_C_CY: STD_LOGIC;
	signal PS_STORE_ADDR_REGS_OP_DOT_T_DOT_C_CY: STD_LOGIC;
	signal PS_RTC_BUSY: STD_LOGIC;
	signal MS_RTC_BUSY: STD_LOGIC;

-- START USER TEST BENCH DECLARATIONS

-- The user test bench declarations, if any, must be
-- placed AFTER the line starts with the first line of text 
-- with -- START USER TEST BENCH DECLARATIONS and ends
-- with the line containing -- END (and the rest of the line) below.
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

   constant HDL_C_BIT: integer := 7;
   constant HDL_WM_BIT: integer := 6;
   constant HDL_B_BIT: integer := 5;
   constant HDL_A_BIT: integer := 4;
   constant HDL_8_BIT: integer := 3;
   constant HDL_4_BIT: integer := 2;
   constant HDL_2_BIT: integer := 1;
   constant HDL_1_BIT: integer := 0;

procedure check1(
    checked: in STD_LOGIC;
    val: in STD_LOGIC;
    testname: in string;
    test: in string) is
    begin    
    assert checked = val report testname & " (" & test & ") failed." severity failure;
    end procedure;
      


   -- Your test bench declarations go here

-- END USER TEST BENCH DECLARATIONS

	begin

	-- Instantiate the Unit Under Test (UUT)

	UUT: ALD_14_15_23_1_REAL_TIME_CLOCK_CONTROLS port map(
		FPGA_CLK => FPGA_CLK,
		PS_T_SYMBOL_OP_MODIFIER => PS_T_SYMBOL_OP_MODIFIER,
		PS_C_CYCLE => PS_C_CYCLE,
		MS_REAL_TIME_CLOCK_0_DIGIT => MS_REAL_TIME_CLOCK_0_DIGIT,
		MS_REAL_TIME_CLOCK_1_DIGIT => MS_REAL_TIME_CLOCK_1_DIGIT,
		MS_REAL_TIME_CLOCK_2_DIGIT => MS_REAL_TIME_CLOCK_2_DIGIT,
		MS_REAL_TIME_CLOCK_3_DIGIT => MS_REAL_TIME_CLOCK_3_DIGIT,
		MS_REAL_TIME_CLOCK_4_DIGIT => MS_REAL_TIME_CLOCK_4_DIGIT,
		MS_REAL_TIME_CLOCK_5_DIGIT => MS_REAL_TIME_CLOCK_5_DIGIT,
		MS_REAL_TIME_CLOCK_6_DIGIT => MS_REAL_TIME_CLOCK_6_DIGIT,
		MS_REAL_TIME_CLOCK_7_DIGIT => MS_REAL_TIME_CLOCK_7_DIGIT,
		MS_REAL_TIME_CLOCK_8_DIGIT => MS_REAL_TIME_CLOCK_8_DIGIT,
		PS_STORE_ADDR_REGS_OP_CODE => PS_STORE_ADDR_REGS_OP_CODE,
		MS_REAL_TIME_CLOCK_9_DIGIT => MS_REAL_TIME_CLOCK_9_DIGIT,
		MS_A_RING_6_TIME => MS_A_RING_6_TIME,
		PS_LOGIC_GATE_C_1 => PS_LOGIC_GATE_C_1,
		PS_I_RING_7_TIME => PS_I_RING_7_TIME,
		PS_I_CYCLE => PS_I_CYCLE,
		PS_LOGIC_GATE_F_1 => PS_LOGIC_GATE_F_1,
		MS_I_RING_6_TIME => MS_I_RING_6_TIME,
		MV_36_VOLTS => MV_36_VOLTS,
		SWITCH_REL_RTC_BUSY => SWITCH_REL_RTC_BUSY,
		MS_STORE_ADDR_REGS_OP_DOT_T_DOT_C_CY => MS_STORE_ADDR_REGS_OP_DOT_T_DOT_C_CY,
		PS_STORE_ADDR_REGS_OP_DOT_T_DOT_C_CY => PS_STORE_ADDR_REGS_OP_DOT_T_DOT_C_CY,
		PS_RTC_BUSY => PS_RTC_BUSY,
		MS_RTC_BUSY => MS_RTC_BUSY);

-- START USER TEST BENCH PROCESS

-- The user test bench code MUST be placed between the
-- line that starts with the first line of text that
-- begins with "-- START USERS TEST BENCH PROCESS" 
-- and ends with "-- END"
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

-- 
-- TestBenchFPGAClock.vhdl
--
-- Process to simulate the FPGA clock for a VHDL test bench
--

fpga_clk_process: process

   constant clk_period : time := 10 ns;

   begin
      fpga_clk <= '0';
      wait for clk_period / 2;
      fpga_clk <= '1';
      wait for clk_period / 2;
   end process;

--
-- End of TestBenchFPGAClock.vhdl
--   

-- Place your test bench code in the uut_process

uut_process: process

   variable testName: string(1 to 18);
   variable subtest: integer;

   begin

   -- Your test bench code

   wait;
   end process;

-- The following is needed for older VHDL simulations to
-- terminate the simulation process.  If your environment
-- does not need it, it may be deleted.

stop_simulation: process
   begin
   wait for 100 us;  -- Determines how long your simulation runs
   assert false report "Simulation Ended NORMALLY" severity failure;
   end process;

-- END USER TEST BENCH PROCESS

end;
