-- Test Bench VHDL for IBM SMS ALD page 45.50.13.1
-- Title: BACKSPACE CONTROL LATCH
-- IBM Machine Name 1411
-- Generated by GenerateHDL at 11/3/2020 3:51:27 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;  -- For use in test benches only
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity ALD_45_50_13_1_BACKSPACE_CONTROL_LATCH_tb is
end ALD_45_50_13_1_BACKSPACE_CONTROL_LATCH_tb;

architecture behavioral of ALD_45_50_13_1_BACKSPACE_CONTROL_LATCH_tb is

	-- Component Declaration for the Unit Under Test (UUT)

	component ALD_45_50_13_1_BACKSPACE_CONTROL_LATCH
	    Port (
		FPGA_CLK:		 in STD_LOGIC;
		MS_PROGRAM_RESET_4:	 in STD_LOGIC;
		MS_CONS_WM_CONTROL:	 in STD_LOGIC;
		MS_CONSOLE_OUTPUT_ERROR:	 in STD_LOGIC;
		PS_CONS_CYCLE_LATCH_RESET:	 in STD_LOGIC;
		MS_WM_INPUT:	 in STD_LOGIC;
		PS_CONS_ERROR_CONTROL:	 in STD_LOGIC;
		PS_CONS_CHAR_CONTROL:	 in STD_LOGIC;
		PS_CONS_WM_CONTROL:	 in STD_LOGIC;
		MS_CONS_PRINTER_NOT_BUSY:	 in STD_LOGIC;
		PS_CONS_CYCLE_LATCH_SET:	 in STD_LOGIC;
		PS_CONSOLE_OUTPUT_ERROR:	 in STD_LOGIC;
		PS_CONS_BACK_SPACE_CONTROL:	 out STD_LOGIC;
		MS_CONS_BACK_SPACE_CONTROL:	 out STD_LOGIC;
		MS_CONS_ERROR_BACKSPACE_SET:	 out STD_LOGIC);
	end component;

	-- Inputs

	signal FPGA_CLK: STD_LOGIC := '0';
	signal MS_PROGRAM_RESET_4: STD_LOGIC := '1';
	signal MS_CONS_WM_CONTROL: STD_LOGIC := '1';
	signal MS_CONSOLE_OUTPUT_ERROR: STD_LOGIC := '1';
	signal PS_CONS_CYCLE_LATCH_RESET: STD_LOGIC := '0';
	signal MS_WM_INPUT: STD_LOGIC := '1';
	signal PS_CONS_ERROR_CONTROL: STD_LOGIC := '0';
	signal PS_CONS_CHAR_CONTROL: STD_LOGIC := '0';
	signal PS_CONS_WM_CONTROL: STD_LOGIC := '0';
	signal MS_CONS_PRINTER_NOT_BUSY: STD_LOGIC := '1';
	signal PS_CONS_CYCLE_LATCH_SET: STD_LOGIC := '0';
	signal PS_CONSOLE_OUTPUT_ERROR: STD_LOGIC := '0';

	-- Outputs

	signal PS_CONS_BACK_SPACE_CONTROL: STD_LOGIC;
	signal MS_CONS_BACK_SPACE_CONTROL: STD_LOGIC;
	signal MS_CONS_ERROR_BACKSPACE_SET: STD_LOGIC;

-- START USER TEST BENCH DECLARATIONS

-- The user test bench declarations, if any, must be
-- placed AFTER the line starts with the first line of text 
-- with -- START USER TEST BENCH DECLARATIONS and ends
-- with the line containing -- END (and the rest of the line) below.
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

   constant HDL_C_BIT: integer := 7;
   constant HDL_WM_BIT: integer := 6;
   constant HDL_B_BIT: integer := 5;
   constant HDL_A_BIT: integer := 4;
   constant HDL_8_BIT: integer := 3;
   constant HDL_4_BIT: integer := 2;
   constant HDL_2_BIT: integer := 1;
   constant HDL_1_BIT: integer := 0;

   constant MX_X1A_POS: integer := 7;
   constant MX_X6A_POS: integer := 8;

procedure check1(
    checked: in STD_LOGIC;
    val: in STD_LOGIC;
    testname: in string;
    test: in string) is
    begin    
    assert checked = val report testname & " (" & test & ") failed." severity failure;
    end procedure;
      


   -- Your test bench declarations go here

-- END USER TEST BENCH DECLARATIONS
   

	begin

	-- Instantiate the Unit Under Test (UUT)

	UUT: ALD_45_50_13_1_BACKSPACE_CONTROL_LATCH port map(
		FPGA_CLK => FPGA_CLK,
		MS_PROGRAM_RESET_4 => MS_PROGRAM_RESET_4,
		MS_CONS_WM_CONTROL => MS_CONS_WM_CONTROL,
		MS_CONSOLE_OUTPUT_ERROR => MS_CONSOLE_OUTPUT_ERROR,
		PS_CONS_CYCLE_LATCH_RESET => PS_CONS_CYCLE_LATCH_RESET,
		MS_WM_INPUT => MS_WM_INPUT,
		PS_CONS_ERROR_CONTROL => PS_CONS_ERROR_CONTROL,
		PS_CONS_CHAR_CONTROL => PS_CONS_CHAR_CONTROL,
		PS_CONS_WM_CONTROL => PS_CONS_WM_CONTROL,
		MS_CONS_PRINTER_NOT_BUSY => MS_CONS_PRINTER_NOT_BUSY,
		PS_CONS_CYCLE_LATCH_SET => PS_CONS_CYCLE_LATCH_SET,
		PS_CONSOLE_OUTPUT_ERROR => PS_CONSOLE_OUTPUT_ERROR,
		PS_CONS_BACK_SPACE_CONTROL => PS_CONS_BACK_SPACE_CONTROL,
		MS_CONS_BACK_SPACE_CONTROL => MS_CONS_BACK_SPACE_CONTROL,
		MS_CONS_ERROR_BACKSPACE_SET => MS_CONS_ERROR_BACKSPACE_SET);

-- START USER TEST BENCH PROCESS

-- The user test bench code MUST be placed between the
-- line that starts with the first line of text that
-- begins with "-- START USERS TEST BENCH PROCESS" 
-- and ends with "-- END"
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

-- 
-- TestBenchFPGAClock.vhdl
--
-- Process to simulate the FPGA clock for a VHDL test bench
--

fpga_clk_process: process

   constant clk_period : time := 10 ns;

   begin
      fpga_clk <= '0';
      wait for clk_period / 2;
      fpga_clk <= '1';
      wait for clk_period / 2;
   end process;

--
-- End of TestBenchFPGAClock.vhdl
--   

-- Place your test bench code in the uut_process

uut_process: process

   variable testName: string(1 to 18);
   variable subtest: integer;
   variable tv: std_logic_vector(25 downto 0);
   variable a,b,c,d,e,f,g,h,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z: std_logic;
   variable g1, g2, g3, g4, g5, g6, g7, g8, g9, g10: std_logic;

   begin

   -- Your test bench code

   testName := "45.50.13.1        ";

   for tt in 0 to 2**10 loop
      tv := std_logic_vector(to_unsigned(tt,tv'Length));
      b := tv(0);
      c := tv(1);
      d := tv(2);
      e := tv(3);
      f := tv(4);
      g := tv(5);
      h := tv(6);
      j := tv(7);
      k := tv(8);
      l := tv(9);
      
      g1 := k and g and l;
      g2 := k and not j and not e and  h;
      g3 := g1 or g2;
      g4 := (f and d) or (d and not c and g and not b);

      -- Reset
      
      MS_PROGRAM_RESET_4 <= '0';
      wait for 30 ns;
      MS_PROGRAM_RESET_4 <= '1';
      wait for 30 ns;

      check1(PS_CONS_BACK_SPACE_CONTROL,'0',testName,"Init +S Backspace Control");
      check1(MS_CONS_BACK_SPACE_CONTROL,'1',testName,"Init -S Backspace Control");
      
      -- Assign the signals, except one to prevent the latch from resettting
      -- during the set test
      
		MS_CONS_WM_CONTROL <= not b;
      MS_CONSOLE_OUTPUT_ERROR <= not c;
      -- PS_CONS_CYCLE_LATCH_RESET <= d; -- Hold off on this one
      MS_WM_INPUT <= not e;
      PS_CONS_ERROR_CONTROL <= f;
      PS_CONS_CHAR_CONTROL <= g;
      PS_CONS_WM_CONTROL <= h;
      MS_CONS_PRINTER_NOT_BUSY <= not j;
      PS_CONS_CYCLE_LATCH_SET <= k;
      PS_CONSOLE_OUTPUT_ERROR <= l;      
      wait for 30 ns;
      
      check1(MS_CONS_ERROR_BACKSPACE_SET,not(k and g and l),testName,"Cons Error Backspace Set");
      check1(PS_CONS_BACK_SPACE_CONTROL,g3,testName,"Set +S Backspace Control");
      check1(MS_CONS_BACK_SPACE_CONTROL,not PS_CONS_BACK_SPACE_CONTROL,testName,"Set -S Backspace Control");
            
      -- Reset enough signals so the reset test will work.  The latch should be unaffected
      
      PS_CONS_CYCLE_LATCH_SET <= '0';
      wait for 30 ns;
      
      check1(PS_CONS_BACK_SPACE_CONTROL,g3,testName,"Check set +S Backspace Control");
      check1(MS_CONS_BACK_SPACE_CONTROL,not PS_CONS_BACK_SPACE_CONTROL,testName,"Check set -S Backspace Control");
            
      -- Maybe reset the latch
      
      PS_CONS_CYCLE_LATCH_RESET <= d;
      wait for 30 ns;
            
      check1(PS_CONS_BACK_SPACE_CONTROL,g3 and not g4,testName,"Reset +S Backspace Control");
      check1(MS_CONS_BACK_SPACE_CONTROL,not PS_CONS_BACK_SPACE_CONTROL,testName,"Reset -S Backspace Control");
      
      PS_CONS_CYCLE_LATCH_RESET <= '0';   -- Avoid interfering with next iteration.      
      
      
   end loop;

   assert false report "Simulation Ended NORMALLY" severity failure;

   wait;
   end process;

-- The following is needed for older VHDL simulations to
-- terminate the simulation process.  If your environment
-- does not need it, it may be deleted.

stop_simulation: process
   begin
   wait for 2 ms;  -- Determines how long your simulation runs
   assert false report "Simulation Ended NORMALLY (TIMEOUT)" severity failure;
   end process;

-- END USER TEST BENCH PROCESS
   

end;
