-- Test BenchVHDL for IBM SMS ALD group EditTranslator
-- Title: EditTranslator
-- IBM Machine Name 1411
-- Generated by GenerateHDL on 10/6/2020 8:08:24 PM

-- Included from HDLTemplate.vhdl

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;  -- For use in test benches only
use WORK.ALL;

-- End of include from HDLTemplate.vhdl

entity EditTranslator_tb is
end EditTranslator_tb;

architecture behavioral of EditTranslator_tb is

	-- Component Declaration for the Unit Under Test (UUT)

	component EditTranslator
	    Port (
		FPGA_CLK: in STD_LOGIC;
		PS_B_CH_NOT_8_AND_NOT_1_BIT: in STD_LOGIC;
		PS_B_CH_NOT_4_AND_NOT_2_BIT: in STD_LOGIC;
		PS_B_CYCLE: in STD_LOGIC;
		PS_EDIT_OP_CODE: in STD_LOGIC;
		PS_MOVE_ZERO_SUP_OP_CODE: in STD_LOGIC;
		PS_B_CH_B_AND_A_BIT: in STD_LOGIC;
		PS_B_CH_NOT_8_AND_1_BIT: in STD_LOGIC;
		PS_B_CH_NOT_4_AND_2_BIT: in STD_LOGIC;
		PS_B_CH_8_AND_1_BIT: in STD_LOGIC;
		PS_B_CH_B_AND_NOT_A_BIT: in STD_LOGIC;
		PS_B_CH_NOT_B_AND_NOT_A_BIT: in STD_LOGIC;
		PS_B_CH_8_AND_NOT_1_BIT: in STD_LOGIC;
		PS_B_CH_NOT_B_AND_A_BIT: in STD_LOGIC;
		PS_1ST_SCAN: in STD_LOGIC;
		PS_B_CH_4_AND_NOT_2_BIT: in STD_LOGIC;
		PS_B_CH_NOT_BUS: in STD_LOGIC_VECTOR (7 downTo 0);
		PS_B_CH_BUS: in STD_LOGIC_VECTOR (7 downTo 0);
		PS_NOT_CTRL_0: out STD_LOGIC;
		PS_NOT_ASTERISK: out STD_LOGIC;
		PS_NOT_DOLLAR_SIGN: out STD_LOGIC;
		PS_NOT_SIG_DIGIT: out STD_LOGIC;
		PS_NOT_COMMA: out STD_LOGIC;
		PS_NOT_MINUS_SYMBOL: out STD_LOGIC;
		PS_NOT_DECIMAL: out STD_LOGIC;
		MS_NOT_DECIMAL: out STD_LOGIC;
		PS_NOT_BLANK: out STD_LOGIC;
		PS_NOT_C_CHAR: out STD_LOGIC;
		PS_NOT_R_CHAR: out STD_LOGIC;
		PS_NOT_SPACE: out STD_LOGIC;
		PS_Z_OP_DOT_B_CYCLE: out STD_LOGIC;
		MS_Z_OP_DOT_B_CYCLE: out STD_LOGIC;
		PS_E_OR_Z_OP_DOT_B_CYCLE: out STD_LOGIC;
		PS_E_OP_DOT_B_CYCLE_1: out STD_LOGIC;
		PS_E_OP_DOT_B_CYCLE_2: out STD_LOGIC;
		PS_C_OR_R_OR_MINUS: out STD_LOGIC;
		MS_BLANK: out STD_LOGIC;
		MS_CONTROL_ZERO: out STD_LOGIC;
		PS_BLANK: out STD_LOGIC;
		PS_BLANK_OR_ZERO: out STD_LOGIC;
		PS_CONTROL_ZERO: out STD_LOGIC;
		PS_COMMA: out STD_LOGIC;
		PS_BLANK_0_OR_COMMA: out STD_LOGIC;
		PS_0_OR_DECIMAL: out STD_LOGIC;
		PS_BLK_0_PUNCT_OR_SIG_DIGIT: out STD_LOGIC;
		MS_SIG_DIGIT: out STD_LOGIC;
		PS_SIG_DIGIT: out STD_LOGIC;
		PS_DECIMAL: out STD_LOGIC;
		PS_ASTERISK: out STD_LOGIC;
		PS_ASTERISK_OR_DOLLAR_SIGN: out STD_LOGIC;
		PS_DOLLAR_SIGN: out STD_LOGIC;
		MS_SPACE: out STD_LOGIC);
	end component;

	-- Inputs

	signal FPGA_CLK: STD_LOGIC := '0';
	signal PS_B_CH_NOT_8_AND_NOT_1_BIT: STD_LOGIC := '0';
	signal PS_B_CH_NOT_4_AND_NOT_2_BIT: STD_LOGIC := '0';
	signal PS_B_CYCLE: STD_LOGIC := '0';
	signal PS_EDIT_OP_CODE: STD_LOGIC := '0';
	signal PS_MOVE_ZERO_SUP_OP_CODE: STD_LOGIC := '0';
	signal PS_B_CH_B_AND_A_BIT: STD_LOGIC := '0';
	signal PS_B_CH_NOT_8_AND_1_BIT: STD_LOGIC := '0';
	signal PS_B_CH_NOT_4_AND_2_BIT: STD_LOGIC := '0';
	signal PS_B_CH_8_AND_1_BIT: STD_LOGIC := '0';
	signal PS_B_CH_B_AND_NOT_A_BIT: STD_LOGIC := '0';
	signal PS_B_CH_NOT_B_AND_NOT_A_BIT: STD_LOGIC := '0';
	signal PS_B_CH_8_AND_NOT_1_BIT: STD_LOGIC := '0';
	signal PS_B_CH_NOT_B_AND_A_BIT: STD_LOGIC := '0';
	signal PS_1ST_SCAN: STD_LOGIC := '0';
	signal PS_B_CH_4_AND_NOT_2_BIT: STD_LOGIC := '0';
	signal PS_B_CH_NOT_BUS: STD_LOGIC_VECTOR (7 downTo 0) := "00000000";
	signal PS_B_CH_BUS: STD_LOGIC_VECTOR (7 downTo 0) := "00000000";

	-- Outputs

	signal PS_NOT_CTRL_0: STD_LOGIC;
	signal PS_NOT_ASTERISK: STD_LOGIC;
	signal PS_NOT_DOLLAR_SIGN: STD_LOGIC;
	signal PS_NOT_SIG_DIGIT: STD_LOGIC;
	signal PS_NOT_COMMA: STD_LOGIC;
	signal PS_NOT_MINUS_SYMBOL: STD_LOGIC;
	signal PS_NOT_DECIMAL: STD_LOGIC;
	signal MS_NOT_DECIMAL: STD_LOGIC;
	signal PS_NOT_BLANK: STD_LOGIC;
	signal PS_NOT_C_CHAR: STD_LOGIC;
	signal PS_NOT_R_CHAR: STD_LOGIC;
	signal PS_NOT_SPACE: STD_LOGIC;
	signal PS_Z_OP_DOT_B_CYCLE: STD_LOGIC;
	signal MS_Z_OP_DOT_B_CYCLE: STD_LOGIC;
	signal PS_E_OR_Z_OP_DOT_B_CYCLE: STD_LOGIC;
	signal PS_E_OP_DOT_B_CYCLE_1: STD_LOGIC;
	signal PS_E_OP_DOT_B_CYCLE_2: STD_LOGIC;
	signal PS_C_OR_R_OR_MINUS: STD_LOGIC;
	signal MS_BLANK: STD_LOGIC;
	signal MS_CONTROL_ZERO: STD_LOGIC;
	signal PS_BLANK: STD_LOGIC;
	signal PS_BLANK_OR_ZERO: STD_LOGIC;
	signal PS_CONTROL_ZERO: STD_LOGIC;
	signal PS_COMMA: STD_LOGIC;
	signal PS_BLANK_0_OR_COMMA: STD_LOGIC;
	signal PS_0_OR_DECIMAL: STD_LOGIC;
	signal PS_BLK_0_PUNCT_OR_SIG_DIGIT: STD_LOGIC;
	signal MS_SIG_DIGIT: STD_LOGIC;
	signal PS_SIG_DIGIT: STD_LOGIC;
	signal PS_DECIMAL: STD_LOGIC;
	signal PS_ASTERISK: STD_LOGIC;
	signal PS_ASTERISK_OR_DOLLAR_SIGN: STD_LOGIC;
	signal PS_DOLLAR_SIGN: STD_LOGIC;
	signal MS_SPACE: STD_LOGIC;

-- START USER TEST BENCH DECLARATIONS

-- The user test bench declarations, if any, must be
-- placed AFTER the line starts with the first line of text 
-- with -- START USER TEST BENCH DECLARATIONS and ends
-- with the line containing -- END (and the rest of the line) below.
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

   constant HDL_C_BIT: integer := 7;
   constant HDL_WM_BIT: integer := 6;
   constant HDL_B_BIT: integer := 5;
   constant HDL_A_BIT: integer := 4;
   constant HDL_8_BIT: integer := 3;
   constant HDL_4_BIT: integer := 2;
   constant HDL_2_BIT: integer := 1;
   constant HDL_1_BIT: integer := 0;

   constant MX_X1A_POS: integer := 7;
   constant MX_X6A_POS: integer := 8;

procedure check1(
    checked: in STD_LOGIC;
    val: in STD_LOGIC;
    testname: in string;
    test: in string) is
    begin    
    assert checked = val report testname & " (" & test & ") failed." severity failure;
    end procedure;
      


   -- Your test bench declarations go here

-- END USER TEST BENCH DECLARATIONS
   

	begin

	-- Instantiate the Unit Under Test (UUT)

	UUT: EditTranslator port map(
		FPGA_CLK => FPGA_CLK,
		PS_B_CH_NOT_8_AND_NOT_1_BIT => PS_B_CH_NOT_8_AND_NOT_1_BIT,
		PS_B_CH_NOT_4_AND_NOT_2_BIT => PS_B_CH_NOT_4_AND_NOT_2_BIT,
		PS_B_CYCLE => PS_B_CYCLE,
		PS_EDIT_OP_CODE => PS_EDIT_OP_CODE,
		PS_MOVE_ZERO_SUP_OP_CODE => PS_MOVE_ZERO_SUP_OP_CODE,
		PS_B_CH_B_AND_A_BIT => PS_B_CH_B_AND_A_BIT,
		PS_B_CH_NOT_8_AND_1_BIT => PS_B_CH_NOT_8_AND_1_BIT,
		PS_B_CH_NOT_4_AND_2_BIT => PS_B_CH_NOT_4_AND_2_BIT,
		PS_B_CH_8_AND_1_BIT => PS_B_CH_8_AND_1_BIT,
		PS_B_CH_B_AND_NOT_A_BIT => PS_B_CH_B_AND_NOT_A_BIT,
		PS_B_CH_NOT_B_AND_NOT_A_BIT => PS_B_CH_NOT_B_AND_NOT_A_BIT,
		PS_B_CH_8_AND_NOT_1_BIT => PS_B_CH_8_AND_NOT_1_BIT,
		PS_B_CH_NOT_B_AND_A_BIT => PS_B_CH_NOT_B_AND_A_BIT,
		PS_1ST_SCAN => PS_1ST_SCAN,
		PS_B_CH_4_AND_NOT_2_BIT => PS_B_CH_4_AND_NOT_2_BIT,
		PS_B_CH_NOT_BUS => PS_B_CH_NOT_BUS,
		PS_B_CH_BUS => PS_B_CH_BUS,
		PS_NOT_CTRL_0 => PS_NOT_CTRL_0,
		PS_NOT_ASTERISK => PS_NOT_ASTERISK,
		PS_NOT_DOLLAR_SIGN => PS_NOT_DOLLAR_SIGN,
		PS_NOT_SIG_DIGIT => PS_NOT_SIG_DIGIT,
		PS_NOT_COMMA => PS_NOT_COMMA,
		PS_NOT_MINUS_SYMBOL => PS_NOT_MINUS_SYMBOL,
		PS_NOT_DECIMAL => PS_NOT_DECIMAL,
		MS_NOT_DECIMAL => MS_NOT_DECIMAL,
		PS_NOT_BLANK => PS_NOT_BLANK,
		PS_NOT_C_CHAR => PS_NOT_C_CHAR,
		PS_NOT_R_CHAR => PS_NOT_R_CHAR,
		PS_NOT_SPACE => PS_NOT_SPACE,
		PS_Z_OP_DOT_B_CYCLE => PS_Z_OP_DOT_B_CYCLE,
		MS_Z_OP_DOT_B_CYCLE => MS_Z_OP_DOT_B_CYCLE,
		PS_E_OR_Z_OP_DOT_B_CYCLE => PS_E_OR_Z_OP_DOT_B_CYCLE,
		PS_E_OP_DOT_B_CYCLE_1 => PS_E_OP_DOT_B_CYCLE_1,
		PS_E_OP_DOT_B_CYCLE_2 => PS_E_OP_DOT_B_CYCLE_2,
		PS_C_OR_R_OR_MINUS => PS_C_OR_R_OR_MINUS,
		MS_BLANK => MS_BLANK,
		MS_CONTROL_ZERO => MS_CONTROL_ZERO,
		PS_BLANK => PS_BLANK,
		PS_BLANK_OR_ZERO => PS_BLANK_OR_ZERO,
		PS_CONTROL_ZERO => PS_CONTROL_ZERO,
		PS_COMMA => PS_COMMA,
		PS_BLANK_0_OR_COMMA => PS_BLANK_0_OR_COMMA,
		PS_0_OR_DECIMAL => PS_0_OR_DECIMAL,
		PS_BLK_0_PUNCT_OR_SIG_DIGIT => PS_BLK_0_PUNCT_OR_SIG_DIGIT,
		MS_SIG_DIGIT => MS_SIG_DIGIT,
		PS_SIG_DIGIT => PS_SIG_DIGIT,
		PS_DECIMAL => PS_DECIMAL,
		PS_ASTERISK => PS_ASTERISK,
		PS_ASTERISK_OR_DOLLAR_SIGN => PS_ASTERISK_OR_DOLLAR_SIGN,
		PS_DOLLAR_SIGN => PS_DOLLAR_SIGN,
		MS_SPACE => MS_SPACE);

-- START USER TEST BENCH PROCESS

PS_B_CH_NOT_BUS <= NOT PS_B_CH_BUS;      

PS_B_CH_B_AND_A_BIT <= PS_B_CH_BUS(HDL_B_BIT) and PS_B_CH_BUS(HDL_A_BIT);
PS_B_CH_8_AND_1_BIT <= PS_B_CH_BUS(HDL_8_BIT) and PS_B_CH_BUS(HDL_1_BIT);
PS_B_CH_B_AND_NOT_A_BIT <= PS_B_CH_BUS(HDL_B_BIT) and PS_B_CH_NOT_BUS(HDL_A_BIT);
PS_B_CH_8_AND_NOT_1_BIT <= PS_B_CH_BUS(HDL_8_BIT) and PS_B_CH_NOT_BUS(HDL_1_BIT);
PS_B_CH_4_AND_NOT_2_BIT <= PS_B_CH_BUS(HDL_4_BIT) and PS_B_CH_NOT_BUS(HDL_2_BIT);
PS_B_CH_NOT_B_AND_A_BIT <= PS_B_CH_NOT_BUS(HDL_B_BIT) and PS_B_CH_BUS(HDL_A_BIT);
PS_B_CH_NOT_8_AND_1_BIT <= PS_B_CH_NOT_BUS(HDL_8_BIT) and PS_B_CH_BUS(HDL_1_BIT);
PS_B_CH_NOT_4_AND_2_BIT <= PS_B_CH_NOT_BUS(HDL_4_BIT) and PS_B_CH_BUS(HDL_2_BIT);
PS_B_CH_NOT_B_AND_NOT_A_BIT <= PS_B_CH_NOT_BUS(HDL_B_BIT) and PS_B_CH_NOT_BUS(HDL_A_BIT);
PS_B_CH_NOT_8_AND_NOT_1_BIT <= PS_B_CH_NOT_BUS(HDL_8_BIT) and PS_B_CH_NOT_BUS(HDL_1_BIT);
PS_B_CH_NOT_4_AND_NOT_2_BIT <= PS_B_CH_NOT_BUS(HDL_4_BIT) and PS_B_CH_NOT_BUS(HDL_2_BIT);



-- The user test bench code MUST be placed between the
-- line that starts with the first line of text that
-- begins with "-- START USERS TEST BENCH PROCESS" 
-- and ends with "-- END"
-- This text is preserved when the IBM1410SMS applciation
-- regenerates a test bench

-- 
-- TestBenchFPGAClock.vhdl
--
-- Process to simulate the FPGA clock for a VHDL test bench
--


fpga_clk_process: process

   constant clk_period : time := 10 ns;

   begin
      fpga_clk <= '0';
      wait for clk_period / 2;
      fpga_clk <= '1';
      wait for clk_period / 2;
   end process;

--
-- End of TestBenchFPGAClock.vhdl
--   

-- Place your test bench code in the uut_process

uut_process: process

   variable testName: string(1 to 18);
   variable subtest: integer;
   variable tv: std_logic_vector(25 downto 0);
   variable a,b,c,d,e,f,g,h,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z: std_logic;
   variable g1, g2, g3, g4, g5, g6, g7, g8, g9, g10: std_logic;

   begin

   -- Your test bench code

   testName := "17.11.0%.1        ";

   for BCD_CHAR in BCD.BCD loop
      PS_B_CH_BUS <= BCD.bcd_to_slv8_odd_parity(BCD_CHAR);
      wait for 30 ns;
      
      case BCD_CHAR is
         when BCD.BCD_0 => 
            check1(PS_NOT_CTRL_0,'0',testName,"Not Ctrl 0 false");
            check1(PS_CONTROL_ZERO,'1',testName,"+S Control 0 asserted");
            check1(MS_CONTROL_ZERO,'0',testName,"-S Control 0 asserted");
         when Others => 
            check1(PS_NOT_CTRL_0,'1',testName,"Not Ctrl 0 true");
            check1(PS_CONTROL_ZERO,'0',testName,"+S Control 0 Not Asserted");
            check1(MS_CONTROL_ZERO,'1',testName,"-S Control 0 Not Asserted");
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_ASTERISK => 
            check1(PS_NOT_ASTERISK,'0',testName,"Not * false");
            check1(PS_ASTERISK,'1',testName,"+S * asserted");      
         when others => 
            check1(PS_NOT_ASTERISK,'1',testName,"Not * true");
            check1(PS_ASTERISK,'0',testName,"+S * not asserted");                  
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_DOLLAR => 
            check1(PS_NOT_DOLLAR_SIGN,'0',testName,"Not $ False");
            check1(PS_DOLLAR_SIGN,'1',testName,"+S $ Asserted");
         when others => 
            check1(PS_NOT_DOLLAR_SIGN,'1',testName,"Not $ true");
            check1(PS_DOLLAR_SIGN,'0',testName,"+S $ Not Asserted");            
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_1 to BCD.BCD_9 => 
            check1(PS_NOT_SIG_DIGIT,'0',testName,"Not digit false 1-9");
            check1(PS_SIG_DIGIT,'1',testName,"+S Sig Digit Asserted");
            check1(MS_SIG_DIGIT,'0',testName,"-S Sig Digit Asserted");
         when others => 
            check1(PS_NOT_SIG_DIGIT,'1',testName,"Not digit true");
            check1(PS_SIG_DIGIT,'0',testName,"+S Sig Digit Not Asserted");
            check1(MS_SIG_DIGIT,'1',testName,"-S Sig Digit Not Asserted");
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_MINUS => check1(PS_NOT_MINUS_SYMBOL,'0',testName,"Not Minus false");
         when others => check1(PS_NOT_MINUS_SYMBOL,'1',testName,"Not Minus true");
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_COMMA => 
            check1(PS_NOT_COMMA,'0',testName,"Not Comma false");
            check1(PS_COMMA,'1',testName,"+S Comma Asserted");
         when others => 
            check1(PS_NOT_COMMA,'1',testName,"Not Comma true");
            check1(PS_COMMA,'0',testName,"+S Comman Not Asserted");
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_PERIOD => 
            check1(PS_NOT_DECIMAL,'0',testName,"Not Decimal false");
            check1(MS_NOT_DECIMAL,'1',testName,"-S Not Decimal false");
            check1(PS_DECIMAL,'1',testName,"+S Decimal Asserted");
         when others => 
            check1(PS_NOT_DECIMAL,'1',testName,"Not Decimal true");
            check1(MS_NOT_DECIMAL,'0',testName,"-S Not Decimal true");
            check1(PS_DECIMAL,'0',testName,"+S Decimal Not Asserted");
      end case;

      case BCD_CHAR is
         when BCD.BCD_BLANK => 
            check1(PS_NOT_BLANK,'0',testName,"Not Blank false");
            check1(PS_BLANK,'1',testName,"+S Blank asserted");
            check1(MS_BLANK,'0',testName,"-S Blank asserted");
         when others => 
            check1(PS_NOT_BLANK,'1',testName,"Not BLANK true");
            check1(PS_BLANK,'0',testName,"+S Blank Not Assserted");
            check1(MS_BLANK,'1',testName,"-S Blank Not Assserted");
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_C => check1(PS_NOT_C_CHAR,'0',testName,"Not C false");
         when others => check1(PS_NOT_C_CHAR,'1',testName,"Not C true");
      end case;

      case BCD_CHAR is
         when BCD.BCD_R => check1(PS_NOT_R_CHAR,'0',testName,"Not R false");
         when others => check1(PS_NOT_R_CHAR,'1',testName,"Not R true");
      end case;

      case BCD_CHAR is
         when BCD.BCD_AMPERSAND => 
            check1(PS_NOT_SPACE,'0',testName,"Not Space (&) false");
         when others => check1(PS_NOT_SPACE,'1',testName,"Not Space (&) true");
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_C | BCD.BCD_R | BCD.BCD_MINUS =>
            check1(PS_C_OR_R_OR_MINUS,'1',testName,"C or R or Minus true");
         when others => check1(PS_C_OR_R_OR_MINUS,'0',testName,"C or R or Minus false");
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_BLANK | BCD.BCD_0 =>
            check1(PS_BLANK_OR_ZERO,'1',testName,"+S Blank or Zero true");
         when others => check1(PS_BLANK_OR_ZERO,'0',testName,"+S Blank or Zero false");
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_BLANK | BCD.BCD_0 | BCD.BCD_COMMA =>
            check1(PS_BLANK_0_OR_COMMA,'1',testName,"+S Blank 0 or Comma true");
         when others => check1(PS_BLANK_0_OR_COMMA,'0',testName,"+S Blank 0 or Comma false");
      end case;

      case BCD_CHAR is
         when BCD.BCD_0 | BCD.BCD_PERIOD =>
            check1(PS_0_OR_DECIMAL,'1',testName,"+S 0 or Decimal true");
         when others => check1(PS_0_OR_DECIMAL,'0',testName,"+S 0 or Decimal false");
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_1 to BCD.BCD_9 | BCD.BCD_BLANK | BCD.BCD_0 | BCD.BCD_COMMA | BCD.BCD_MINUS |
            BCD.BCD_PERIOD =>
               check1(PS_BLK_0_PUNCT_OR_SIG_DIGIT,'1',testName,"+ Blank 0 Punc. or digit true");
         when others => 
               check1(PS_BLK_0_PUNCT_OR_SIG_DIGIT,'0',testName,"+ Blank 0 Punc. or digit false");
      end case;
      
      case BCD_CHAR is
         when BCD.BCD_ASTERISK | BCD.BCD_DOLLAR => 
            check1(PS_ASTERISK_OR_DOLLAR_SIGN,'1',testName,"+S * or $ asserted");      
         when others => 
            check1(PS_ASTERISK_OR_DOLLAR_SIGN,'0',testName,"+S * not asserted");                  
      end case;      
            
   end loop;
   
   for tt in 0 to 16 loop
      tv := std_logic_vector(to_unsigned(tt,tv'Length));
      a := tv(0);
      b := tv(1);
      c := tv(2);
      d := tv(3);
      
      PS_MOVE_ZERO_SUP_OP_CODE <= a;
      PS_B_CYCLE <= b;
      PS_EDIT_OP_CODE <= c;
      PS_1ST_SCAN <= d;
      wait for 30 ns;
      
      check1(PS_Z_OP_DOT_B_CYCLE,a and b,testName,"Z Op.B");
      check1(MS_Z_OP_DOT_B_CYCLE,NOT(a and b),testName,"-S Z Op.B");
      check1(PS_E_OR_Z_OP_DOT_B_CYCLE,b and (a or c),testName,"E+Z Op . B");
      check1(PS_E_OP_DOT_B_CYCLE_1,c and b,testName,"E Op . B 1");
      check1(PS_E_OP_DOT_B_CYCLE_2,c and b,testName,"E Op . B 2");
      
      for BCD_CHAR in BCD.BCD loop
         PS_B_CH_BUS <= BCD.bcd_to_slv8_odd_parity(BCD_CHAR);
         wait for 30 ns;
         
         case BCD_CHAR is
            when BCD.BCD_AMPERSAND => 
               check1(MS_SPACE,not(PS_E_OP_DOT_B_CYCLE_1 and d),
                  testName,"-S Space perhaps asserted");
            when others => 
               check1(MS_SPACE,'1',testName,"-S Space (&) not asserted");
         end case;

         wait for 30 ns;
      end loop;      
      
   end loop;

   assert false report "Simulation Ended NORMALLY" severity failure;

   wait;
   end process;

-- The following is needed for older VHDL simulations to
-- terminate the simulation process.  If your environment
-- does not need it, it may be deleted.

stop_simulation: process
   begin
   wait for 2 ms;  -- Determines how long your simulation runs
   assert false report "Simulation Ended NORMALLY (TIMEOUT)" severity failure;
   end process;

-- END USER TEST BENCH PROCESS
   

END;
